var k;k||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ca=!!globalThis.WorkerGlobalScope,da=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",ea=[],fa="./this.program",ha=(a,b)=>{throw b;},ia=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ia=__filename:ca&&(ia=self.location.href);var ja="",ka,la;
if(da){var fs=require("node:fs");ja=__dirname+"/";la=a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a)};ka=async a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);typeof module!="undefined"&&(module.exports=k);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ca){try{ja=(new URL(".",ia)).href}catch{}ca&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ka=async a=>{if(ma(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var na=console.log.bind(console),m=console.error.bind(console),oa,pa=!1,qa,ma=a=>a.startsWith("file://");
function ra(){var a=sa.buffer;n=new Int8Array(a);p=new Int16Array(a);r=new Uint8Array(a);ta=new Uint16Array(a);t=new Int32Array(a);u=new Uint32Array(a);ua=new Float32Array(a);v=new Float64Array(a);w=new BigInt64Array(a);new BigUint64Array(a)}function va(a){k.onAbort?.(a);a=`Aborted(${a})`;m(a);pa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var wa;
async function xa(a){if(!oa)try{var b=await ka(a);return new Uint8Array(b)}catch{}if(a==wa&&oa)a=new Uint8Array(oa);else if(la)a=la(a);else throw"both async and sync fetching of the wasm failed";return a}async function ya(a,b){try{var c=await xa(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),va(d)}}
async function za(a){var b=wa;if(!oa&&!ma(b)&&!da)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return ya(b,a)}class Aa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var p,t,w,n,ua,v,ta,u,r,Ba=a=>{for(;a.length>0;)a.shift()(k)},Ca=[],Da=[],Ea=()=>{var a=k.preRun.shift();Da.push(a)},Fa=0,Ga=null,Ha=!0;
class Ia{constructor(a){this.qd=a-24}init(a,b){u[this.qd+16>>2]=0;u[this.qd+4>>2]=a;u[this.qd+8>>2]=b}}
var Ja=0,Ka=()=>{if(da){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>(crypto.getRandomValues(b),0)},La=a=>(La=Ka())(a),Ma=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Na=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=Ma(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Oa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Pa=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Qa=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=Ma(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ra=globalThis.TextDecoder&&new TextDecoder,y=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&Ra)return Ra.decode(a.subarray(b,
d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Sa=[],Ta=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},z=(a,b,c,d)=>{if(!(d>0))return 0;var e=
c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(c>=d)break;b[c++]=g}else if(g<=2047){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(g<=65535){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Ua=[];function Va(a,b){Ua[a]={input:[],output:[],Lc:b};Wa(a,Xa)}
var Xa={open(a){var b=Ua[a.node.rdev];if(!b)throw new A(43);a.tty=b;a.seekable=!1},close(a){a.tty.Lc.fsync(a.tty)},fsync(a){a.tty.Lc.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Lc.Sd)throw new A(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Lc.Sd(a.tty)}catch(h){throw new A(29);}if(g===void 0&&e===0)throw new A(6);if(g===null||g===void 0)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Lc.yd)throw new A(60);try{for(var e=0;e<d;e++)a.tty.Lc.yd(a.tty,b[c+e])}catch(f){throw new A(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Ya={Sd(){a:{if(!Sa.length){var a=null;if(da){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}c>0&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}b=Array(Ta(a)+1);a=z(a,b,0,b.length);b.length=a;Sa=b}a=Sa.shift()}return a},yd(a,b){b===null||b===10?(na(y(a.output)),a.output=
[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(na(y(a.output)),a.output=[])},ke(){return{Be:25856,De:5,Ae:191,Ce:35387,ze:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},le(){return 0},me(){return[24,80]}},Za={yd(a,b){b===null||b===10?(m(y(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(m(y(a.output)),a.output=[])}},C={Hc:null,Gc(){return C.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new A(63);
C.Hc||(C.Hc={dir:{node:{Bc:C.rc.Bc,Nc:C.rc.Nc,lookup:C.rc.lookup,md:C.rc.md,rename:C.rc.rename,unlink:C.rc.unlink,rmdir:C.rc.rmdir,readdir:C.rc.readdir,symlink:C.rc.symlink},stream:{Fc:C.sc.Fc}},file:{node:{Bc:C.rc.Bc,Nc:C.rc.Nc},stream:{Fc:C.sc.Fc,read:C.sc.read,write:C.sc.write,Vd:C.sc.Vd,Xd:C.sc.Xd}},link:{node:{Bc:C.rc.Bc,Nc:C.rc.Nc,readlink:C.rc.readlink},stream:{}},Ld:{node:{Bc:C.rc.Bc,Nc:C.rc.Nc},stream:$a}});c=ab(a,b,c,d);E(c.mode)?(c.rc=C.Hc.dir.node,c.sc=C.Hc.dir.stream,c.uc={}):(c.mode&
61440)===32768?(c.rc=C.Hc.file.node,c.sc=C.Hc.file.stream,c.zc=0,c.uc=C.ee??(C.ee=new Uint8Array(0))):(c.mode&61440)===40960?(c.rc=C.Hc.link.node,c.sc=C.Hc.link.stream):(c.mode&61440)===8192&&(c.rc=C.Hc.Ld.node,c.sc=C.Hc.Ld.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.uc[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},rc:{Bc(a){var b={};b.dev=(a.mode&61440)===8192?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;E(a.mode)?b.size=4096:(a.mode&61440)===32768?b.size=a.zc:(a.mode&
61440)===40960?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Nc(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.zc!=b&&(c=a.uc,a.uc=new Uint8Array(b),a.uc.set(c.subarray(0,Math.min(b,a.zc))),a.zc=b))},lookup(){C.sd||(C.sd=new A(44),C.sd.stack="<generic error, no stack>");throw C.sd;},md(a,b,c,d){return C.createNode(a,b,c,
d)},rename(a,b,c){try{var d=F(b,c)}catch(f){}if(d){if(E(a.mode))for(var e in d.uc)throw new A(55);bb(d)}delete a.parent.uc[a.name];b.uc[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.uc[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=F(a,b),d;for(d in c.uc)throw new A(55);delete a.uc[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.uc)]},symlink(a,b,c){a=C.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if((a.mode&61440)!==
40960)throw new A(28);return a.link}},sc:{read(a,b,c,d,e){if(e>=a.node.zc)return 0;d=Math.min(a.node.zc-e,d);b.set(a.node.uc.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===n.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(f)a.uc=b.subarray(c,c+d),a.zc=d;else if(a.zc===0&&e===0)a.uc=b.slice(c,c+d),a.zc=d;else{f=e+d;var g=a.uc.length;g>=f||(f=Math.max(f,g*(g<1048576?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.uc.subarray(0,a.zc),a.uc=new Uint8Array(f),a.uc.set(g));a.uc.set(b.subarray(c,
c+d),e);a.zc=Math.max(a.zc,e+d)}return d},Fc(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.zc);if(b<0)throw new A(28);return b},Vd(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new A(43);a=a.node.uc;if(e&2||a.buffer!==n.buffer){d=!0;va();e=void 0;if(!e)throw new A(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);n.set(a,e)}}else d=!1,e=a.byteOffset;return{qd:e,Sc:d}},Xd(a,b,c,d){C.sc.write(a,b,0,d,c,!1);return 0}}},cb=
(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},db=null,eb={},fb=[],gb=1,G=null,hb=!1,ib=!0,A=class{name="ErrnoError";constructor(a){this.tc=a}},jb=class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},kb=class{rc={};sc={};Uc=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Gc=a.Gc;this.id=gb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return(this.mode&
365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}};
function H(a,b={}){if(!a)throw new A(44);b.ud??(b.ud=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(h=>!!h);for(var d=db,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=Oa(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Na(e+"/"+a[f]);try{d=F(d,a[f])}catch(h){if(h?.tc===44&&g&&b.qe)return{path:e};throw h;}!d.Uc||g&&!b.ud||(d=d.Uc.root);if((d.mode&61440)===40960&&(!g||b.ad)){if(!d.rc.readlink)throw new A(52);
d=d.rc.readlink(d);d.charAt(0)==="/"||(d=Oa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new A(32);}function lb(a){for(var b;;){if(a===a.parent)return a=a.Gc.Wd,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function mb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%G.length}
function bb(a){var b=mb(a.parent.id,a.name);if(G[b]===a)G[b]=a.Vc;else for(b=G[b];b;){if(b.Vc===a){b.Vc=a.Vc;break}b=b.Vc}}function F(a,b){var c=E(a.mode)?(c=nb(a,"x"))?c:a.rc.lookup?0:2:54;if(c)throw new A(c);for(c=G[mb(a.id,b)];c;c=c.Vc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.rc.lookup(a,b)}function ab(a,b,c,d){a=new kb(a,b,c,d);b=mb(a.parent.id,a.name);a.Vc=G[b];return G[b]=a}function E(a){return(a&61440)===16384}
function nb(a,b){return ib?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function ob(a,b){if(!E(a.mode))return 54;try{return F(a,b),20}catch(c){}return nb(a,"wx")}function pb(a,b,c){try{var d=F(a,b)}catch(e){return e.tc}if(a=nb(a,"wx"))return a;if(c){if(!E(d.mode))return 54;if(d===d.parent||lb(d)==="/")return 10}else if(E(d.mode))return 31;return 0}function qb(a,b){if(!a)throw new A(b);return a}
function I(a){a=fb[a];if(!a)throw new A(8);return a}function rb(a,b=-1){a=Object.assign(new jb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!fb[b])break a;throw new A(33);}a.fd=b;return fb[b]=a}function sb(a,b=-1){a=rb(a,b);a.sc?.Ke?.(a);return a}function tb(a,b){var c=void 0,d=c?null:a;c??=a.rc.Nc;qb(c,63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new A(22);throw e;}}var $a={open(a){a.sc=eb[a.node.rdev].sc;a.sc.open?.(a)},Fc(){throw new A(70);}};function Wa(a,b){eb[a]={sc:b}}
function ub(a,b){var c=b==="/";if(c&&db)throw new A(10);if(!c&&b){var d=H(b,{ud:!1});b=d.path;d=d.node;if(d.Uc)throw new A(10);if(!E(d.mode))throw new A(54);}b={type:a,Re:{},Wd:b,oe:[]};a=a.Gc(b);a.Gc=b;b.root=a;c?db=a:d&&(d.Uc=b,d.Gc&&d.Gc.oe.push(b));return a}function vb(a,b,c){var d=H(a,{parent:!0}).node;a=Pa(a);if(!a)throw new A(28);if(a==="."||a==="..")throw new A(20);var e=ob(d,a);if(e)throw new A(e);if(!d.rc.md)throw new A(63);return d.rc.md(d,a,b,c)}
function J(a,b=511){return vb(a,b&1023|16384,0)}function wb(a,b,c){typeof c=="undefined"&&(c=b,b=438);vb(a,b|8192,c)}function xb(a,b){if(!Qa(a))throw new A(44);var c=H(b,{parent:!0}).node;if(!c)throw new A(44);b=Pa(b);var d=ob(c,b);if(d)throw new A(d);if(!c.rc.symlink)throw new A(63);c.rc.symlink(c,b,a)}function yb(a){var b=H(a,{parent:!0}).node;a=Pa(a);var c=F(b,a),d=pb(b,a,!0);if(d)throw new A(d);if(!b.rc.rmdir)throw new A(63);if(c.Uc)throw new A(10);b.rc.rmdir(b,a);bb(c)}
function zb(a,b){a=H(a,{ad:!b}).node;return qb(a.rc.Bc,63)(a)}
function Ab(a,b,c=438){if(a==="")throw new A(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var f=H(a,{ad:!(b&131072),qe:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new A(20);}else{if(e)throw new A(31);d=vb(a,c|511,0);f=!0}if(!d)throw new A(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!E(d.mode))throw new A(54);
if(!f&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=E(d.mode)&&(e!=="r"||b&576)?31:nb(d,e)):e=44,e))throw new A(e);if(b&512&&!f){e=d;e=typeof e=="string"?H(e,{ad:!0}).node:e;if(E(e.mode))throw new A(31);if((e.mode&61440)!==32768)throw new A(28);if(a=nb(e,"w"))throw new A(a);tb(e,{size:0,timestamp:Date.now()})}b=rb({node:d,path:lb(d),flags:b&-131713,seekable:!0,position:0,sc:d.sc,ue:[],error:!1});b.sc.open&&b.sc.open(b);f&&(c&=511,d=typeof d=="string"?H(d,{ad:!0}).node:d,
tb(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),Je:void 0}));return b}function Bb(a,b,c){if(a.fd===null)throw new A(8);if(!a.seekable||!a.sc.Fc)throw new A(70);if(c!=0&&c!=1&&c!=2)throw new A(28);a.position=a.sc.Fc(a,b,c);a.ue=[];return a.position}
function Cb(a,b,c,d){var e=n;if(c<0||d<0)throw new A(28);if(a.fd===null)throw new A(8);if((a.flags&2097155)===0)throw new A(8);if(E(a.node.mode))throw new A(31);if(!a.sc.write)throw new A(28);a.seekable&&a.flags&1024&&Bb(a,0,2);var f=typeof d!="undefined";if(!f)d=a.position;else if(!a.seekable)throw new A(70);b=a.sc.write(a,e,b,c,d,void 0);f||(a.position+=b);return b}
function K(a,b,c){a=Na("/dev/"+a);var d=cb(!!b,!!c);K.Ud??(K.Ud=64);var e=K.Ud++<<8|0;Wa(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,h,l){for(var q=0,x=0;x<l;x++){try{var B=b()}catch(D){throw new A(29);}if(B===void 0&&q===0)throw new A(6);if(B===null||B===void 0)break;q++;g[h+x]=B}q&&(f.node.atime=Date.now());return q},write(f,g,h,l){for(var q=0;q<l;q++)try{c(g[h+q])}catch(x){throw new A(29);}l&&(f.node.mtime=f.node.ctime=Date.now());return q}});wb(a,d,e)}var L={};
function Db(a,b){if(a.type===1&&a.wc)throw new A(53);var c=a.Wc.shift();if(!c){if(a.type===1){a=a.Mc[a.Cc+":"+a.Dc];if(!a)throw new A(53);if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null}throw new A(6);}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,f=c.data.buffer||c.data;b=Math.min(b,d);var g={buffer:new Uint8Array(f,e,b),vc:c.vc,port:c.port};a.type===1&&b<d&&(c.data=new Uint8Array(f,e+b,d-b),a.Wc.unshift(c));return g}
function Eb(a,b,c,d,e,f){if(a.type===2){if(e===void 0||f===void 0)e=a.Cc,f=a.Dc;if(e===void 0||f===void 0)throw new A(17);}else e=a.Cc,f=a.Dc;var g=a.Mc[e+":"+f];if(a.type===1&&(!g||g.socket.readyState===g.socket.CLOSING||g.socket.readyState===g.socket.CLOSED))throw new A(53);ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);if(!g||g.socket.readyState!==g.socket.OPEN)return a.type===2&&(g&&g.socket.readyState!==g.socket.CLOSING&&g.socket.readyState!==g.socket.CLOSED||(g=Fb(a,e,
f))),g.od.push(b),d;try{return g.socket.send(b),d}catch(h){throw new A(28);}}
function Gb(a,b){function c(){a.Md=!1;M.emit("open",a.stream.fd);try{for(var f=b.od.shift();f;)b.socket.send(f),f=b.od.shift()}catch(g){b.socket.close()}}function d(f){if(typeof f=="string")f=(new TextEncoder).encode(f);else{if(f.byteLength==0)return;f=new Uint8Array(f)}var g=e;e=!1;g&&f.length===10&&f[0]===255&&f[1]===255&&f[2]===255&&f[3]===255&&f[4]===112&&f[5]===111&&f[6]===114&&f[7]===116?(f=f[8]<<8|f[9],delete a.Mc[b.vc+":"+b.port],b.port=f,a.Mc[b.vc+":"+b.port]=b):(a.Wc.push({vc:b.vc,port:b.port,
data:f}),M.emit("message",a.stream.fd))}var e=!0;da?(b.socket.on("open",c),b.socket.on("message",(f,g)=>{g&&d((new Uint8Array(f)).buffer)}),b.socket.on("close",()=>M.emit("close",a.stream.fd)),b.socket.on("error",()=>{a.error=14;M.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})):(b.socket.onopen=c,b.socket.onclose=()=>M.emit("close",a.stream.fd),b.socket.onmessage=f=>d(f.data),b.socket.onerror=()=>{a.error=14;M.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})}
function Fb(a,b,c){if(typeof b=="object"){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e="ws://".replace("#","//"),f="binary",g=void 0;M.Zc.url&&(e=M.Zc.url);M.Zc.subprotocol?f=M.Zc.subprotocol:M.Zc.subprotocol===null&&(f="null");if(e==="ws://"||e==="wss://"){var h=b.split("/");e=e+h[0]+":"+c+"/"+
h.slice(1).join("/")}f!=="null"&&(g=f=f.replace(/^ +| +$/g,"").split(/ *, */));d=new (da?require("ws"):WebSocket)(e,g);d.binaryType="arraybuffer"}catch(l){throw new A(23);}b={vc:b,port:c,socket:d,od:[]};a.Mc[b.vc+":"+b.port]=b;Gb(a,b);a.type===2&&typeof a.Yc!="undefined"&&b.od.push(new Uint8Array([255,255,255,255,112,111,114,116,(a.Yc&65280)>>8,a.Yc&255]));return b}
var M={Zc:{},Jd:{},on(a,b){M.Jd[a]=b},emit(a,b){M.Jd[a]?.(b)},Gc(){M.Zc=k.websocket||{};var a;((a=k).websocket??(a.websocket={})).on=M.on;return ab(null,"/",16895,0)},createSocket(a,b,c){if(a!=2)throw new A(5);b&=-526337;if(b!=1&&b!=2)throw new A(28);if(b==1&&c&&c!=6)throw new A(66);a={family:a,type:b,protocol:c,wc:null,error:null,Mc:{},pending:[],Wc:[],Rc:M.we};b=M.pd();c=ab(M.root,b,49152,0);c.Xc=a;b=rb({path:b,node:c,flags:2,seekable:!1,sc:M.sc});a.stream=b;return a},sc:{Zd(a){a=a.node.Xc;return a.Rc.Zd(a)},
hd(a,b,c){a=a.node.Xc;return a.Rc.hd(a,b,c)},read(a,b,c,d){a=Db(a.node.Xc,d);if(!a)return 0;b.set(a.buffer,c);return a.buffer.length},write(a,b,c,d){return Eb(a.node.Xc,b,c,d)},close(a){a=a.node.Xc;a.Rc.close(a)}},pd(){M.pd.current||(M.pd.current=0);return`socket[${M.pd.current++}]`},we:{Zd(a){if(a.type===1&&a.wc)return a.pending.length?65:0;var b=0,c=a.type===1?a.Mc[a.Cc+":"+a.Dc]:null;if(a.Wc.length||!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=65;if(!c||
c&&c.socket.readyState===c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b=a.Md?b|4:b|16;return b},hd(a,b,c){switch(b){case 21531:return b=0,a.Wc.length&&(b=a.Wc[0].data.length),t[c>>2]=b,0;case 21537:return a.stream.flags=t[c>>2]?a.stream.flags|2048:a.stream.flags&-2049,0;default:return 28}},close(a){if(a.wc){try{a.wc.close()}catch(c){}a.wc=null}for(var b of Object.values(a.Mc)){try{b.socket.close()}catch(c){}delete a.Mc[b.vc+":"+b.port]}return 0},
bind(a,b,c){if(typeof a.zd!="undefined"||typeof a.Yc!="undefined")throw new A(28);a.zd=b;a.Yc=c;if(a.type===2){a.wc&&(a.wc.close(),a.wc=null);try{a.Rc.listen(a,0)}catch(d){if(d.name!=="ErrnoError")throw d;if(d.tc!==138)throw d;}}},connect(a,b,c){if(a.wc)throw new A(138);if(typeof a.Cc!="undefined"&&typeof a.Dc!="undefined"){var d=a.Mc[a.Cc+":"+a.Dc];if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new A(7);throw new A(30);}}b=Fb(a,b,c);a.Cc=b.vc;a.Dc=b.port;a.Md=!0},listen(a){if(!da)throw new A(138);
if(a.wc)throw new A(28);var b=require("ws").Server;a.wc=new b({host:a.zd,port:a.Yc});M.emit("listen",a.stream.fd);a.wc.on("connection",c=>{if(a.type===1){var d=M.createSocket(a.family,a.type,a.protocol);c=Fb(d,c);d.Cc=c.vc;d.Dc=c.port;a.pending.push(d);M.emit("connection",d.stream.fd)}else Fb(a,c),M.emit("connection",a.stream.fd)});a.wc.on("close",()=>{M.emit("close",a.stream.fd);a.wc=null});a.wc.on("error",()=>{a.error=23;M.emit("error",[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},
accept(a){if(!a.wc||!a.pending.length)throw new A(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Oe(a,b){if(b){if(a.Cc===void 0||a.Dc===void 0)throw new A(53);b=a.Cc;a=a.Dc}else b=a.zd||0,a=a.Yc||0;return{vc:b,port:a}}}},Hb=a=>{a=(a=fb[a])&&(a.node.mode&49152)===49152?a.node.Xc:null;if(!a)throw new A(8);return a},Ib=a=>{a=a.split(".");for(var b=0;b<4;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},Kb=a=>{var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;
if(a==="::")return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");a.indexOf(".")>0?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=Number(a[a.length-4])+Number(a[a.length-3])*256,a[a.length-3]=Number(a[a.length-2])+Number(a[a.length-1])*256,a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if(typeof a[b]=="string")if(a[b]==="Z"){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=Jb(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<
16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},Lb=(a,b,c,d,e)=>{switch(b){case 2:c=Ib(c);r.fill(0,a,a+16);e&&(t[e>>2]=16);p[a>>1]=b;t[a+4>>2]=c;p[a+2>>1]=Jb(d);break;case 10:c=Kb(c),r.fill(0,a,a+28),e&&(t[e>>2]=28),t[a>>2]=b,t[a+8>>2]=c[0],t[a+12>>2]=c[1],t[a+16>>2]=c[2],t[a+20>>2]=c[3],p[a+2>>1]=Jb(d)}},Mb=1,Nb={},Ob={};function Pb(a){var b=Ib(a);if(b!==null)return a;b=Kb(a);if(b!==null)return a;Nb[a]?b=Nb[a]:(b=Mb++,b="172.29."+(b&255)+"."+(b&65280),Ob[b]=a,Nb[a]=b);return b}
var Qb=a=>(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255),Sb=(a,b)=>{var c=p[a>>1],d=Rb(ta[a+2>>1]);switch(c){case 2:if(b!==16)return{tc:28};var e=t[a+4>>2];e=Qb(e);break;case 10:if(b!==28)return{tc:28};e=[t[a+8>>2],t[a+12>>2],t[a+16>>2],t[a+20>>2]];a:{a="";var f,g=b=0,h=0,l=0;e=[e[0]&65535,e[0]>>16,e[1]&65535,e[1]>>16,e[2]&65535,e[2]>>16,e[3]&65535,e[3]>>16];var q=!0;for(f=0;f<5;f++)if(e[f]!==0){q=!1;break}if(q){f=Qb(e[6]|e[7]<<16);if(e[5]===-1){e="::ffff:"+f;break a}if(e[5]===0){f==="0.0.0.0"&&
(f="");f==="0.0.0.1"&&(f="1");e="::"+f;break a}}for(f=0;f<8;f++)e[f]===0&&(f-g>1&&(l=0),g=f,l++),l>b&&(b=l,h=f-b+1);for(f=0;f<8;f++)b>1&&e[f]===0&&f>=h&&f<h+b?f===h&&(a+=":",h===0&&(a+=":")):(a+=Number(Rb(e[f]&65535)).toString(16),a+=f<7?":":"");e=a}break;default:return{tc:5}}return{family:c,vc:e,port:d}},Tb=(a,b)=>{a=Sb(a,b);if(a.tc)throw new A(a.tc);b=a.vc;a.vc=(Ob[b]?Ob[b]:null)||a.vc;return a},N=()=>{var a=t[+Ub>>2];Ub+=4;return a};
function Vb(a,b,c){if(b.charAt(0)==="/")return b;a=a===-100?"/":I(a).path;if(b.length==0){if(!c)throw new A(44);return a}return a+"/"+b}
function Wb(a,b){u[a>>2]=b.dev;u[a+4>>2]=b.mode;u[a+8>>2]=b.nlink;u[a+12>>2]=b.uid;u[a+16>>2]=b.gid;u[a+20>>2]=b.rdev;w[a+24>>3]=BigInt(b.size);t[a+32>>2]=4096;t[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();w[a+40>>3]=BigInt(Math.floor(c/1E3));u[a+48>>2]=c%1E3*1E3*1E3;w[a+56>>3]=BigInt(Math.floor(d/1E3));u[a+64>>2]=d%1E3*1E3*1E3;w[a+72>>3]=BigInt(Math.floor(e/1E3));u[a+80>>2]=e%1E3*1E3*1E3;w[a+88>>3]=BigInt(b.ino);return 0}
var Ub=void 0,Xb=[0,31,60,91,121,152,182,213,244,274,305,335],Yb=[0,31,59,90,120,151,181,212,243,273,304,334],Zb=[],$b=(a,b)=>{Zb.length=0;for(var c;c=r[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;Zb.push(c==112?u[b>>2]:c==106?w[b>>3]:c==105?t[b>>2]:v[b>>3]);b+=d?8:4}return Zb},jc=(a,b)=>{ac=a;bc=b;if(cc)if(dc||=!0,a==0)O=function(){setTimeout(ec,Math.max(0,fc+b-performance.now())|0)};else if(a==1)O=function(){hc(ec)};else{if(!ic)if(globalThis.scheduler)ic=scheduler.postTask.bind(scheduler);else if(globalThis.setImmediate)ic=
setImmediate;else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);ic=d=>{c.push(d);ca?postMessage("setimmediate"):postMessage("setimmediate","*")}}O=function(){ic(ec)}}},kc=a=>{qa=a;Ha||(k.onExit?.(a),pa=!0);ha(a,new Aa(a))},lc=a=>{a instanceof Aa||a=="unwind"||ha(1,a)},mc=()=>{if(!Ha)try{var a=qa;qa=a;kc(a)}catch(b){lc(b)}},vc=(a,b,c,d,e)=>{function f(){return g<nc?(mc(),!1):!0}cc=a;oc=d;var g=nc;dc=!1;ec=function(){if(!pa)if(pc.length>0){var h=
pc.shift();h.Me(h.xe);if(qc){var l=qc,q=l%1==0?l-1:Math.floor(l);qc=h.Fe?q:(8*l+(q+.5))/9}k.setStatus&&(h=k.statusMessage||"Please wait...",l=qc??0,q=rc.Le??0,l?l<q?k.setStatus("{message} ({expected - remaining}/{expected})"):k.setStatus(h):k.setStatus(""));f()&&setTimeout(ec,0)}else if(f())if(sc=sc+1|0,ac==1&&bc>1&&sc%bc!=0)O();else{ac==0&&(fc=performance.now());a:if(!pa){for(h of tc)if(h()===!1)break a;if(!pa)try{a()}catch(x){lc(x)}finally{mc()}for(l of uc)l()}f()&&O()}};e||(b>0?jc(0,1E3/b):jc(1,
1),O());if(c)throw"unwind";},dc=!1,O=null,nc=0,cc=null,oc=0,ac=0,bc=0,sc=0,pc=[],tc=[],uc=[];function wc(){O=null;nc++}var xc=0;function hc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(xc===0)xc=b+1E3/60;else for(;b+2>=xc;)xc+=1E3/60;setTimeout(a,Math.max(xc-b,0))}}var rc={},fc,ec,ic,qc;function yc(a){var b=P.xc[a];b.target.removeEventListener(b.yc,b.Rd,b.Ic);P.xc.splice(a,1)}
function zc(a){function b(e,f){if(e.length!=f.length)return!1;for(var g in e)if(e[g]!=f[g])return!1;return!0}var c=Ac,d;for(d of P.Pc)if(d.Cd==c&&b(d.Id,a))return;P.Pc.push({Cd:c,$d:1,Id:a});P.Pc.sort((e,f)=>e.$d-f.$d)}function Bc(){var a=Ac;P.Pc=P.Pc.filter(b=>b.Cd!=a)}function Cc(){if(navigator.userActivation?navigator.userActivation.isActive:P.gd&&P.Nd.dd){var a=P.Pc;P.Pc=[];for(var b of a)b.Cd(...b.Id)}}
function Q(a){if(!a.target)return-4;if(a.Ac)a.Rd=function(c){++P.gd;P.Nd=a;Cc();a.Kc(c);Cc();--P.gd},a.target.addEventListener(a.yc,a.Rd,a.Ic),P.xc.push(a);else for(var b=0;b<P.xc.length;++b)P.xc[b].target==a.target&&P.xc[b].yc==a.yc&&yc(b--);return 0}function Dc(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var P={ye:0,Ne:0,wd:0,nd:0,Hd:0,Ed:0,td:0,He:0,Se:0,Ge:0,vd:0,xd:0,Gd:0,Dd:0,Ue(){for(;P.xc.length;)yc(P.xc.length-1);P.Pc=[]},gd:0,Pc:[],xc:[],se:(a,b)=>{for(var c=0;c<P.xc.length;++c)P.xc[c].target!=a||b&&b!=P.xc[c].yc||yc(c--)},Ve(a){var b=!1;for(let c=0;c<P.xc.length;++c){let d=P.xc[c];d.target===a.target&&d.Ec===a.Ec&&d.Ac===a.Ac&&d.Jc===a.Jc&&(yc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Ec=[0,globalThis.document??0,globalThis.window??
0],R=a=>{a=a>2?a?y(r,a):"":a;return Ec[a]||globalThis.document?.querySelector(a)},Gc=a=>{var b=Ta(a)+1,c=Fc(b);z(a,r,c,b);return c},Jc=a=>{var b=Hc(),c=Fc(8),d=c+4;a=Gc(a.id);if(a=R(a))t[c>>2]=a.width,t[d>>2]=a.height;c=[t[c>>2],t[d>>2]];Ic(b);return c},Kc=(a,b,c)=>{a=R(a);if(!a)return-4;a.width=b;a.height=c;return 0},Lc=(a,b,c)=>{if(a.Ee){var d=Hc();a=Gc(a.id);Kc(a,b,c);Ic(d)}else a.width=b,a.height=c},Mc={},Nc=[],S=a=>{var b=Nc[a];b||(Nc[a]=b=Oc.get(a));return b},Qc=a=>{function b(){Pc()||(document.removeEventListener("fullscreenchange",
b),document.removeEventListener("webkitfullscreenchange",b),Lc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=h,l||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=l,a.style.paddingLeft=q,a.style.paddingRight=x,a.style.paddingTop=B,a.style.paddingBottom=D,a.style.marginLeft=ba,a.style.marginRight=Hd,a.style.marginTop=Id,a.style.marginBottom=Jd,document.body.style.margin=Kd,document.documentElement.style.overflow=Ld,document.body.scroll=Md,a.style.imageRendering=
Nd,a.$c&&a.$c.Oc.viewport(0,0,d,e),Mc.ed&&S(Mc.ed)(37,0,Mc.Kd))}var c=Jc(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,h=a.style.backgroundColor,l=document.body.style.backgroundColor,q=a.style.paddingLeft,x=a.style.paddingRight,B=a.style.paddingTop,D=a.style.paddingBottom,ba=a.style.marginLeft,Hd=a.style.marginRight,Id=a.style.marginTop,Jd=a.style.marginBottom,Kd=document.body.style.margin,Ld=document.documentElement.style.overflow,Md=document.body.scroll,Nd=a.style.imageRendering;document.addEventListener("fullscreenchange",
b);document.addEventListener("webkitfullscreenchange",b)},Rc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Sc=a=>Ec.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},Ac=(a,b)=>{if(b.Ad!=0||b.rd!=0){Qc(a);var c=b.te?innerWidth:screen.width,d=b.te?innerHeight:screen.height,e=Sc(a),f=e.width;e=e.height;var g=Jc(a),h=g[0];g=g[1];b.Ad==3?(Rc(a,(d-e)/2,(c-f)/2),c=f,d=e):b.Ad==2&&(c*g<h*d?(f=g*c/h,Rc(a,(d-f)/2,0),d=f):(f=h*d/g,Rc(a,0,(c-f)/
2),c=f));var l;(l=a.style).backgroundColor||(l.backgroundColor="black");let q;(q=document.body.style).backgroundColor||(q.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";b.ie==1&&(a.style.imageRendering="optimizeSpeed",a.style.imageRendering="-moz-crisp-edges",a.style.imageRendering="-o-crisp-edges",a.style.imageRendering="-webkit-optimize-contrast",a.style.imageRendering="optimize-contrast",a.style.imageRendering="crisp-edges",a.style.imageRendering="pixelated");l=b.rd==2?devicePixelRatio:
1;b.rd!=0&&(c=c*l|0,d=d*l|0,Lc(a,c,d),a.$c&&a.$c.Oc.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return P.fullscreenEnabled()?-3:-1;Mc=b;b.ed&&S(b.ed)(37,0,b.Kd);return 0};function Pc(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var Tc=(a,b)=>{if(!P.fullscreenEnabled())return-1;a=R(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?(navigator.userActivation?navigator.userActivation.isActive:P.gd&&P.Nd.dd)?Ac(a,b):b.de?(zc([a,b]),1):-2:-3:-4},Uc=(a,b,c,d,e,f)=>{P.td||(P.td=T(256));a={target:R(a),yc:f,Ec:e,Jc:b,Ac:d,Kc:g=>{var h=g.target.id??"",l=P.td;z(Dc(g.target),r,l+0,128);z(h,r,l+128,128);S(d)(e,l,b)&&g.preventDefault()},Ic:c};return Q(a)},Vc=(a,b,c,d,e)=>{P.vd||(P.vd=T(276));return Q({target:a,yc:e,Ec:19,Jc:b,
Ac:d,Kc:f=>{var g=P.vd,h=Pc(),l=!!h;n[g]=l;n[g+1]=P.fullscreenEnabled();var q=l?h:P.re,x=q?.id??"";z(Dc(q),r,g+2,128);z(x,r,g+130,128);t[g+260>>2]=q?.clientWidth??0;t[g+264>>2]=q?.clientHeight??0;t[g+268>>2]=screen.width;t[g+272>>2]=screen.height;l&&(P.re=h);S(d)(19,g,b)&&f.preventDefault()},Ic:c})},Wc=(a,b,c,d,e,f)=>{P.wd||(P.wd=T(160));a={target:R(a),yc:f,Ec:e,Jc:b,Ac:d,Kc:g=>{var h=P.wd;v[h>>3]=g.timeStamp;var l=h>>2;t[l+2]=g.location;n[h+12]=g.ctrlKey;n[h+13]=g.shiftKey;n[h+14]=g.altKey;n[h+15]=
g.metaKey;n[h+16]=g.repeat;t[l+5]=g.charCode;t[l+6]=g.keyCode;t[l+7]=g.which;z(g.key??"",r,h+32,32);z(g.code??"",r,h+64,32);z(g.char??"",r,h+96,32);z(g.locale??"",r,h+128,32);S(d)(e,h,b)&&g.preventDefault()},Ic:c};return Q(a)},Xc=(a,b,c)=>{v[a>>3]=b.timeStamp;var d=a>>2;t[d+2]=b.screenX;t[d+3]=b.screenY;t[d+4]=b.clientX;t[d+5]=b.clientY;n[a+24]=b.ctrlKey;n[a+25]=b.shiftKey;n[a+26]=b.altKey;n[a+27]=b.metaKey;p[d*2+14]=b.button;p[d*2+15]=b.buttons;t[d+8]=b.movementX;t[d+9]=b.movementY;a=Sc(c);t[d+10]=
b.clientX-(a.left|0);t[d+11]=b.clientY-(a.top|0)},Yc=(a,b,c,d,e,f)=>{P.nd||(P.nd=T(64));a=R(a);return Q({target:a,dd:f!="mousemove"&&f!="mouseenter"&&f!="mouseleave",yc:f,Ec:e,Jc:b,Ac:d,Kc:g=>{Xc(P.nd,g,a);S(d)(e,P.nd,b)&&g.preventDefault()},Ic:c})},Zc=(a,b,c,d)=>{P.xd||(P.xd=T(257));return Q({target:a,yc:"pointerlockchange",Ec:20,Jc:b,Ac:d,Kc:e=>{var f=P.xd,g=document.pointerLockElement;n[f]=!!g;var h=g?.id??"";z(Dc(g),r,f+1,128);z(h,r,f+129,128);S(d)(20,f,b)&&e.preventDefault()},Ic:c})},$c=(a,b,
c,d)=>{P.Ed||(P.Ed=T(36));a=R(a);return Q({target:a,yc:"resize",Ec:10,Jc:b,Ac:d,Kc:e=>{if(e.target==a){var f=document.body;if(f){var g=P.Ed;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=pageYOffset|0;S(d)(10,g,b)&&e.preventDefault()}}},Ic:c})},ad=(a,b,c,d,e,f)=>{P.Dd||(P.Dd=T(1552));a=R(a);return Q({target:a,dd:f=="touchstart"||f=="touchend",yc:f,Ec:e,Jc:b,Ac:d,
Kc:g=>{var h={},l=g.touches;for(var q of l)q.Td=q.Yd=0,h[q.identifier]=q;for(var x of g.changedTouches)x.Td=1,h[x.identifier]=x;for(var B of g.targetTouches)h[B.identifier].Yd=1;l=P.Dd;v[l>>3]=g.timeStamp;n[l+12]=g.ctrlKey;n[l+13]=g.shiftKey;n[l+14]=g.altKey;n[l+15]=g.metaKey;q=l+16;x=Sc(a);B=0;for(let D of Object.values(h))if(h=q>>2,t[h]=D.identifier,t[h+1]=D.screenX,t[h+2]=D.screenY,t[h+3]=D.clientX,t[h+4]=D.clientY,t[h+5]=D.pageX,t[h+6]=D.pageY,n[q+28]=D.Td,n[q+29]=D.Yd,t[h+8]=D.clientX-(x.left|
0),t[h+9]=D.clientY-(x.top|0),q+=48,++B>31)break;t[l+8>>2]=B;S(d)(e,l,b)&&g.preventDefault()},Ic:c})},bd=(a,b,c)=>{var d=Ec[1];P.Gd||(P.Gd=T(8));return Q({target:d,yc:"visibilitychange",Ec:21,Jc:a,Ac:c,Kc:e=>{var f=P.Gd,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);n[f]=document.hidden;t[f+4>>2]=g;S(c)(21,f,a)&&e.preventDefault()},Ic:b})},cd=(a,b,c,d)=>{P.Hd||(P.Hd=T(96));return Q({target:a,dd:!0,yc:"wheel",Ec:9,Jc:b,Ac:d,Kc:e=>{var f=P.Hd;Xc(f,e,a);v[f+64>>3]=e.deltaX;
v[f+72>>3]=e.deltaY;v[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;S(d)(9,f,b)&&e.preventDefault()},Ic:c})},U,dd=a=>{a.Ie=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},ed=a=>{a.Pe=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},fd=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},gd=1,hd=[],V=[],jd=[],kd=[],ld=[],W=[],md=[],X=[],nd=[],od={},pd={},qd=4,rd=0,sd=a=>{for(var b=gd++,c=a.length;c<b;c++)a[c]=null;return b},td=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=U[c](),g=f&&sd(d);f?(f.name=g,d[g]=f):Y||=1282;t[b+e*4>>2]=g}},vd=(a,b)=>{a.bd||(a.bd=a.getContext,a.getContext=function(d,e){e=a.bd(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?ud(c,b):0},ud=
(a,b)=>{var c=sd(X),d={handle:c,attributes:b,version:b.ne,Oc:a};a.canvas&&(a.canvas.$c=d);X[c]=d;if(typeof b.Qd=="undefined"||b.Qd)if((a=d)||(a=Z),!a.je){a.je=!0;b=a.Oc;b.pe=b.getExtension("WEBGL_multi_draw");b.he=b.getExtension("EXT_polygon_offset_clamp");b.ge=b.getExtension("EXT_clip_control");b.ve=b.getExtension("WEBGL_polygon_mode");dd(b);ed(b);a.version>=2&&(b.Pd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(a.version<2||!b.Pd)b.Pd=b.getExtension("EXT_disjoint_timer_query");for(var e of fd(b))e.includes("lose_context")||
e.includes("debug")||b.getExtension(e)}return c},Y,Z,wd=["default","low-power","high-performance"];class xd{Sc=[void 0];bd=[];get(a){return this.Sc[a]}has(a){return this.Sc[a]!==void 0}}var yd=new xd;function zd(a){return yd.has(a)?yd.get(a):0}function Ad(a){this.Bd||(this.Bd=T(520));u[this.Bd>>2]=a;return this.Bd}
var Bd=a=>{var b=Ta(a)+1,c=T(b);c&&z(a,r,c,b);return c},Cd={},Ed=()=>{if(!Dd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:fa},b;for(b in Cd)Cd[b]===void 0?delete a[b]:a[b]=Cd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Dd=c}return Dd},Dd,Fd=(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=u[b>>2],h=u[b+4>>2];b+=8;var l=a;var q=g,x=h,B=d,D=n;if(x<0||B<0)throw new A(28);if(l.fd===null)throw new A(8);
if((l.flags&2097155)===1)throw new A(8);if(E(l.node.mode))throw new A(31);if(!l.sc.read)throw new A(28);g=typeof B!="undefined";if(!g)B=l.position;else if(!l.seekable)throw new A(70);q=l.sc.read(l,D,q,x,B);g||(l.position+=q);l=q;if(l<0)return-1;e+=l;if(l<h)break;typeof d!="undefined"&&(d+=l)}return e},Gd=(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=u[b>>2],h=u[b+4>>2];b+=8;g=Cb(a,g,h,d);if(g<0)return-1;e+=g;if(g<h)break;typeof d!="undefined"&&(d+=g)}return e},Od=[],Pd=()=>{var a=fd(U);return a=a.concat(a.map(b=>
"GL_"+b))},Qd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:c!=0&&c!=1&&(Y||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=U.getParameter(34467);d=e?e.length:0;break;case 33309:if(Z.version<2){Y||=1282;return}d=Pd().length;break;case 33307:case 33308:if(Z.version<2){Y||=1280;return}d=a==33307?3:0}if(d===void 0)switch(e=U.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Y||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:Y||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+a*4>>2]=e[a];break;case 2:ua[b+a*4>>2]=e[a];break;case 4:n[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){Y||=1280;m(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Y||=1280;m(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;u[b>>2]=c;u[b+4>>2]=(c-u[b>>2])/4294967296;break;case 0:t[b>>2]=d;break;case 2:ua[b>>2]=d;break;case 4:n[b]=d?1:0}}else Y||=1281},Rd=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),Sd=a=>{a-=5120;return a==0?n:a==1?r:a==2?p:a==4?t:a==6?ua:a==5||a==28922||a==28520||a==30779||a==30782?u:ta};G=Array(4096);ub(C,"/");J("/tmp");J("/home");J("/home/web_user");
(function(){J("/dev");Wa(259,{read:()=>0,write:(d,e,f,g)=>g,Fc:()=>0});wb("/dev/null",259);Va(1280,Ya);Va(1536,Za);wb("/dev/tty",1280);wb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b===0&&(La(a),b=a.byteLength);return a[--b]};K("random",c);K("urandom",c);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");ub({Gc(){var b=ab(a,"fd",16895,73);b.sc={Fc:C.sc.Fc};b.rc={lookup(c,d){c=+d;var e=I(c);c={parent:null,Gc:{Wd:"fake"},rc:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(fb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();k.requestAnimationFrame=hc;k.pauseMainLoop=wc;k.resumeMainLoop=function(){nc++;var a=ac,b=bc,c=cc;cc=null;vc(c,0,!1,oc,!0);jc(a,b);O()};
k.preMainLoop&&tc.push(k.preMainLoop);k.postMainLoop&&uc.push(k.postMainLoop);for(let a=0;a<32;++a)Od.push(Array(a));k.noExitRuntime&&(Ha=k.noExitRuntime);k.print&&(na=k.print);k.printErr&&(m=k.printErr);k.wasmBinary&&(oa=k.wasmBinary);k.arguments&&(ea=k.arguments);k.thisProgram&&(fa=k.thisProgram);if(k.preInit)for(typeof k.preInit=="function"&&(k.preInit=[k.preInit]);k.preInit.length>0;)k.preInit.shift()();
var Td={931640:a=>{try{let b=new (window.AudioContext||window.webkitAudioContext)({sampleRate:a,latencyHint:"interactive"});k.zyWebAudio=b;a=function(){b.resume()};document.addEventListener("click",a,{once:!0});document.addEventListener("keydown",a,{once:!0});document.addEventListener("touchstart",a,{once:!0});return 1}catch(b){return 0}},932114:()=>{k.zyWebAudio.close()},932148:()=>k.zyWebAudio.currentTime,932193:(a,b,c)=>{var d=k.zyWebAudio,e=d.createBuffer(2,b,d.sampleRate),f=e.getChannelData(0),
g=e.getChannelData(1);a>>=2;for(var h=0;h<b;++h)f[h]=ua[a+h*2],g[h]=ua[a+h*2+1];b=d.createBufferSource();b.buffer=e;b.connect(d.destination);b.start(c)},932687:()=>{k.zyWebAudio.suspend()},932723:()=>{k.zyWebAudio.resume()},932758:(a,b,c)=>{a=a?y(r,a,b):"";console[["debug","info","warn","error"][c]||"log"](a)},932900:(a,b)=>{document.title=a?y(r,a,b):""},932943:a=>{var b=Ec["!ZyWindowHTML5"];b&&(b.style.display=a?"block":"none")},933069:()=>{var a=Ec["!ZyWindowHTML5"];a&&a.focus()},933165:()=>window.devicePixelRatio||
1,933208:()=>{Ec["!ZyWindowHTML5"]=k.canvas},933266:()=>window.devicePixelRatio||1,933309:()=>window.devicePixelRatio||1,933352:()=>window.matchMedia("(dynamic-range: high)").matches?1:0,933420:()=>location.protocol==="https:"?1:0},Ud,Vd,T,Jb,Rb,Ic,Fc,Hc,sa,Oc,Wd={y:(a,b,c)=>{(new Ia(a)).init(b,c);Ja++;va()},vb:function(a,b,c){try{var d=Hb(a),e=d.Rc.accept(d);b&&Lb(b,e.family,Pb(e.Cc),e.Dc,c);return e.stream.fd}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;return-f.tc}},ub:function(a,
b,c){try{var d=Hb(a),e=Tb(b,c);d.Rc.bind(d,e.vc,e.port);return 0}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;return-f.tc}},f:function(a,b,c){Ub=c;try{var d=I(a);switch(b){case 0:var e=N();if(e<0)break;for(;fb[e];)e++;return sb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=N(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=N(),p[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;return-f.tc}},
Nb:function(a,b){try{var c=I(a),d=c.node,e=c.sc.Bc;a=e?c:d;e??=d.rc.Bc;qb(e,63);var f=e(a);return Wb(b,f)}catch(g){if(typeof L=="undefined"||g.name!=="ErrnoError")throw g;return-g.tc}},Ib:function(a,b){try{if(b===0)return-28;var c=Ta("/")+1;if(b<c)return-68;z("/",r,a,b);return c}catch(d){if(typeof L=="undefined"||d.name!=="ErrnoError")throw d;return-d.tc}},Ab:function(a,b,c){try{var d=I(a);if(!d.Qc){var e=H(d.path,{ad:!0}).node;var f=qb(e.rc.readdir,54)(e);d.Qc=f}a=0;var g=Bb(d,0,1),h=Math.floor(g/
280),l=Math.min(d.Qc.length,h+Math.floor(c/280));for(c=h;c<l;c++){var q=d.Qc[c];if(q==="."){var x=d.node.id;var B=4}else if(q==="..")x=H(d.path,{parent:!0}).node.id,B=4;else{try{var D=F(d.node,q)}catch(ba){if(ba?.tc===28)continue;throw ba;}x=D.id;B=(D.mode&61440)===8192?2:E(D.mode)?4:(D.mode&61440)===40960?10:8}w[b+a>>3]=BigInt(x);w[b+a+8>>3]=BigInt((c+1)*280);p[b+a+16>>1]=280;n[b+a+18]=B;z(q,r,b+a+19,256);a+=280}Bb(d,c*280,0);return a}catch(ba){if(typeof L=="undefined"||ba.name!=="ErrnoError")throw ba;
return-ba.tc}},Pb:function(a,b,c){Ub=c;try{var d=I(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Lc.ke){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=N();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;f<32;f++)n[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Lc.le)for(e=N(),a=[],f=0;f<32;f++)a.push(n[e+f+17]);
return 0;case 21519:if(!d.tty)return-59;e=N();return t[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=N();if(!d.sc.hd)throw new A(59);return d.sc.hd(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Lc.me&&(f=[24,80],e=N(),p[e>>1]=f[0],p[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if(typeof L=="undefined"||g.name!=="ErrnoError")throw g;return-g.tc}},tb:function(a,b){try{var c=Hb(a);c.Rc.listen(c,b);return 0}catch(d){if(typeof L==
"undefined"||d.name!=="ErrnoError")throw d;return-d.tc}},Kb:function(a,b){try{return a=a?y(r,a):"",Wb(b,zb(a,!0))}catch(c){if(typeof L=="undefined"||c.name!=="ErrnoError")throw c;return-c.tc}},Fb:function(a,b,c){try{return b=b?y(r,b):"",b=Vb(a,b),J(b,c&-19),0}catch(d){if(typeof L=="undefined"||d.name!=="ErrnoError")throw d;return-d.tc}},Lb:function(a,b,c,d){try{b=b?y(r,b):"";var e=d&256;b=Vb(a,b,d&4096);return Wb(c,e?zb(b,!0):zb(b))}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;
return-f.tc}},V:function(a,b,c,d){Ub=d;try{b=b?y(r,b):"";b=Vb(a,b);var e=d?N():0;c&64&&(e&=-19);return Ab(b,c,e).fd}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;return-f.tc}},sb:function(a,b,c,d,e,f){try{var g=Hb(a),h=Db(g,c);if(!h)return 0;e&&Lb(e,g.family,Pb(h.vc),h.port,f);r.set(h.buffer,b);return h.buffer.byteLength}catch(l){if(typeof L=="undefined"||l.name!=="ErrnoError")throw l;return-l.tc}},xb:function(a){try{return a=a?y(r,a):"",yb(a),0}catch(b){if(typeof L=="undefined"||
b.name!=="ErrnoError")throw b;return-b.tc}},rb:function(a,b,c,d,e,f){try{var g=Hb(a);if(!e)return Cb(g.stream,b,c);var h=Tb(e,f);return Eb(g,n,b,c,h.vc,h.port)}catch(l){if(typeof L=="undefined"||l.name!=="ErrnoError")throw l;return-l.tc}},qb:function(a,b,c){try{return M.createSocket(a,b,c).stream.fd}catch(d){if(typeof L=="undefined"||d.name!=="ErrnoError")throw d;return-d.tc}},Mb:function(a,b){try{return a=a?y(r,a):"",Wb(b,zb(a))}catch(c){if(typeof L=="undefined"||c.name!=="ErrnoError")throw c;return-c.tc}},
zb:function(a,b,c){try{b=b?y(r,b):"";b=Vb(a,b);if(c)if(c===512)yb(b);else return-28;else{a=b;var d=H(a,{parent:!0}).node;if(!d)throw new A(44);var e=Pa(a),f=F(d,e),g=pb(d,e,!1);if(g)throw new A(g);if(!d.rc.unlink)throw new A(63);if(f.Uc)throw new A(10);d.rc.unlink(d,e);bb(f)}return 0}catch(h){if(typeof L=="undefined"||h.name!=="ErrnoError")throw h;return-h.tc}},Ub:()=>va(""),Db:function(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);t[b>>2]=a.getSeconds();t[b+4>>2]=
a.getMinutes();t[b+8>>2]=a.getHours();t[b+12>>2]=a.getDate();t[b+16>>2]=a.getMonth();t[b+20>>2]=a.getFullYear()-1900;t[b+24>>2]=a.getDay();var c=a.getFullYear();t[b+28>>2]=(c%4!==0||c%100===0&&c%400!==0?Yb:Xb)[a.getMonth()]+a.getDate()-1|0;t[b+36>>2]=-(a.getTimezoneOffset()*60);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();t[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Eb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,
0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();u[a>>2]=Math.max(f,e)*60;t[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(z(a,r,c,17),z(b,r,d,17)):(z(a,r,d,17),z(b,r,c,17))},Tb:function(a,b,c){if(!(a>=0&&a<=3))return 28;w[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},q:(a,b,c)=>{b=$b(b,c);return Td[a](...b)},b:(a,b,c)=>{b=$b(b,c);
return Td[a](...b)},wa:(a,b,c)=>{b=$b(b,c);return Td[a](...b)},Vb:()=>{wc();cc=null},Sb:()=>Date.now(),ca:()=>{if(!P.fullscreenEnabled())return-1;Bc();var a=Ec[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},$b:()=>globalThis.devicePixelRatio??1,cc:(a,b,c)=>{a=R(a);if(!a)return-4;a=Sc(a);v[b>>3]=a.width;v[c>>3]=a.height;return 0},c:()=>performance.now(),ac:(a,b)=>{t[a>>2]=screen.width;
t[b>>2]=screen.height},da:(a,b,c)=>Tc(a,{Ad:t[c>>2],rd:t[c+4>>2],ie:t[c+8>>2],de:b,ed:t[c+12>>2],Kd:t[c+16>>2]}),wb:a=>{var b=r.length;a>>>=0;if(a>1073741824)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(1073741824,Math.ceil(Math.max(a,d)/65536)*65536)-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},ia:(a,b,c,d)=>Uc(a,b,c,d,12,"blur"),ba:Kc,dc:(a,b,c)=>{a=R(a);if(!a)return-4;a.style.width=
b+"px";a.style.height=c+"px";return 0},ja:(a,b,c,d)=>Uc(a,b,c,d,13,"focus"),ga:(a,b,c,d)=>{if(!P.fullscreenEnabled())return-1;a=R(a);if(!a)return-4;Vc(a,b,c,d,"webkitfullscreenchange");return Vc(a,b,c,d,"fullscreenchange")},ta:(a,b,c,d)=>Wc(a,b,c,d,2,"keydown"),sa:(a,b,c,d)=>Wc(a,b,c,d,3,"keyup"),bc:(a,b,c,d)=>{vc(()=>S(a)(b),c,d,b)},qa:(a,b,c,d)=>Yc(a,b,c,d,5,"mousedown"),ra:(a,b,c,d)=>Yc(a,b,c,d,8,"mousemove"),pa:(a,b,c,d)=>Yc(a,b,c,d,6,"mouseup"),fa:(a,b,c,d)=>document.body?.requestPointerLock?
(a=R(a))?Zc(a,b,c,d):-4:-1,ha:(a,b,c,d)=>$c(a,b,c,d),ka:(a,b,c,d)=>ad(a,b,c,d,25,"touchcancel"),ma:(a,b,c,d)=>ad(a,b,c,d,23,"touchend"),la:(a,b,c,d)=>ad(a,b,c,d,24,"touchmove"),na:(a,b,c,d)=>ad(a,b,c,d,22,"touchstart"),ea:(a,b,c)=>Ec[1]?bd(a,b,c):-4,oa:(a,b,c,d)=>(a=R(a))?typeof a.onwheel!="undefined"?cd(a,b,c,d):-1:-4,Ba:(a,b)=>{var c=b>>2;b={alpha:!!n[b+0],depth:!!n[b+1],stencil:!!n[b+2],antialias:!!n[b+3],premultipliedAlpha:!!n[b+4],preserveDrawingBuffer:!!n[b+5],powerPreference:wd[t[c+2]],failIfMajorPerformanceCaveat:!!n[b+
12],ne:t[c+4],Qe:t[c+5],Qd:n[b+24],fe:n[b+25],Te:t[c+7],We:n[b+32]};a=R(a);return!a||b.fe?0:vd(a,b)},B:a=>{Z==a&&(Z=0);Z===X[a]&&(Z=null);typeof P=="object"&&P.se(X[a].Oc.canvas);X[a]?.Oc.canvas&&(X[a].Oc.canvas.$c=void 0);X[a]=null},ec:(a,b)=>{a=X[a];b=b?y(r,b):"";b.startsWith("GL_")&&(b=b.slice(3));b=="WEBGL_draw_instanced_base_vertex_base_instance"&&dd(U);b=="WEBGL_multi_draw_instanced_base_vertex_base_instance"&&ed(U);b=="WEBGL_multi_draw"&&(U.pe=U.getExtension("WEBGL_multi_draw"));b=="EXT_polygon_offset_clamp"&&
(U.he=U.getExtension("EXT_polygon_offset_clamp"));b=="EXT_clip_control"&&(U.ge=U.getExtension("EXT_clip_control"));b=="WEBGL_polygon_mode"&&(U.ve=U.getExtension("WEBGL_polygon_mode"));return!!a.Oc.getExtension(b)},fc:()=>Z?Z.handle:0,E:a=>{Z=X[a];k.ctx=U=Z?.Oc;return!a||U?0:-5},_b:(a,b,c)=>{a=zd(a);if(!a)return-3;c&&c&&y(r,c);c?a.close(b||void 0,c?y(r,c):""):b?a.close(b):a.close();return 0},Y:a=>{var b=zd(a);if(!b)return-3;b.onopen=b.onerror=b.onclose=b.onmessage=null;yd.Sc[a]=void 0;yd.bd.push(a);
return 0},Wb:()=>typeof WebSocket!="undefined",Xb:a=>{if(!globalThis.WebSocket)return-1;if(!a)return-5;var b=(b=u[a>>2])?y(r,b):"";a=(a=u[a+4>>2])?new WebSocket(b,(a?y(r,a):"").split(",")):new WebSocket(b);a.binaryType="arraybuffer";b=yd.bd.pop()??yd.Sc.length;yd.Sc[b]=a;return b},Zb:(a,b,c)=>{a=zd(a);if(!a)return-3;a.send(r.subarray(b,b+c));return 0},Z:(a,b,c)=>{var d=zd(a);if(!d)return-3;d.onclose=e=>{var f=Ad(a);n[f+4]=e.wasClean;p[f+6>>1]=e.code;z(e.reason,r,f+8,512);S(c)(0,f,b)};return 0},_:(a,
b,c)=>{var d=zd(a);if(!d)return-3;d.onerror=()=>{var e=Ad(a);S(c)(0,e,b)};return 0},$:(a,b,c)=>{var d=zd(a);if(!d)return-3;d.onmessage=e=>{var f=typeof e.data=="string";if(f)var g=Bd(e.data),h=Ta(e.data)+1;else h=e.data.byteLength,g=T(h),n.set(new Uint8Array(e.data),g);e=Ad(a);u[e+4>>2]=g;t[e+8>>2]=h;n[e+12]=f;S(c)(0,e,b);Vd(g)};return 0},aa:(a,b,c)=>{var d=zd(a);if(!d)return-3;d.onopen=()=>{var e=Ad(a);S(c)(0,e,b)};return 0},Qb:(a,b)=>{var c=0,d=0,e;for(e of Ed()){var f=b+c;u[a+d>>2]=f;c+=z(e,r,
f,Infinity)+1;d+=4}return 0},Rb:(a,b)=>{var c=Ed();u[a>>2]=c.length;a=0;for(var d of c)a+=Ta(d)+1;u[b>>2]=a;return 0},p:function(a){try{var b=I(a);if(b.fd===null)throw new A(8);b.Qc&&(b.Qc=null);try{b.sc.close&&b.sc.close(b)}catch(c){throw c;}finally{fb[b.fd]=null}b.fd=null;return 0}catch(c){if(typeof L=="undefined"||c.name!=="ErrnoError")throw c;return c.tc}},Cb:function(a,b,c,d,e){d=d<-9007199254740992||d>9007199254740992?NaN:Number(d);try{if(isNaN(d))return 22;var f=I(a),g=Fd(f,b,c,d);u[e>>2]=
g;return 0}catch(h){if(typeof L=="undefined"||h.name!=="ErrnoError")throw h;return h.tc}},Bb:function(a,b,c,d,e){d=d<-9007199254740992||d>9007199254740992?NaN:Number(d);try{if(isNaN(d))return 22;var f=I(a),g=Gd(f,b,c,d);u[e>>2]=g;return 0}catch(h){if(typeof L=="undefined"||h.name!=="ErrnoError")throw h;return h.tc}},Ob:function(a,b,c,d){try{var e=I(a),f=Fd(e,b,c);u[d>>2]=f;return 0}catch(g){if(typeof L=="undefined"||g.name!=="ErrnoError")throw g;return g.tc}},Gb:function(a,b,c,d){b=b<-9007199254740992||
b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=I(a);Bb(e,b,c);w[d>>3]=BigInt(e.position);e.Qc&&b===0&&c===0&&(e.Qc=null);return 0}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;return f.tc}},U:function(a,b,c,d){try{var e=I(a),f=Gd(e,b,c);u[d>>2]=f;return 0}catch(g){if(typeof L=="undefined"||g.name!=="ErrnoError")throw g;return g.tc}},X:(a,b,c,d,e,f,g)=>{b=Sb(a,b);if(b.tc)return-6;a=b.port;var h=b.vc;b=!1;if(c&&d){var l;if(g&1||!(l=Ob[h]?Ob[h]:null)){if(g&8)return-2}else h=
l;c=z(h,r,c,d);c+1>=d&&(b=!0)}e&&f&&(c=z(""+a,r,e,f),c+1>=f&&(b=!0));return b?-12:0},Aa:a=>U.activeTexture(a),W:(a,b)=>{U.attachShader(V[a],W[b])},k:(a,b)=>{a==35051?U.Od=b:a==35052&&(U.Tc=b);U.bindBuffer(a,hd[b])},r:(a,b,c)=>{U.bindBufferBase(a,b,hd[c])},s:(a,b,c,d,e)=>{U.bindBufferRange(a,b,hd[c],d,e)},j:(a,b)=>{U.bindFramebuffer(a,jd[b])},L:(a,b)=>{U.bindRenderbuffer(a,kd[b])},za:(a,b)=>{U.bindSampler(a,nd[b])},v:(a,b)=>{U.bindTexture(a,ld[b])},gb:a=>{U.bindVertexArray(md[a])},Ia:(a,b)=>U.blendEquationSeparate(a,
b),Ja:(a,b,c,d)=>U.blendFuncSeparate(a,b,c,d),G:(a,b,c,d,e,f,g,h,l,q)=>U.blitFramebuffer(a,b,c,d,e,f,g,h,l,q),bb:(a,b,c,d)=>{c&&b?U.bufferData(a,r,d,c,b):U.bufferData(a,b,d)},ab:(a,b,c,d)=>{var e=r;c&&U.bufferSubData(a,b,e,d,c)},Qa:(a,b,c,d)=>U.clearBufferfi(a,b,c,d),C:(a,b,c)=>{U.clearBufferfv(a,b,ua,c>>2)},Pa:(a,b,c)=>{U.clearBufferiv(a,b,t,c>>2)},F:(a,b,c,d)=>{U.colorMask(!!a,!!b,!!c,!!d)},ob:a=>{U.compileShader(W[a])},K:(a,b,c,d,e,f,g,h,l)=>{U.Tc||!h?U.compressedTexSubImage2D(a,b,c,d,e,f,g,h,
l):U.compressedTexSubImage2D(a,b,c,d,e,f,g,r,l,h)},H:(a,b,c,d,e,f,g,h,l,q,x)=>{U.Tc?U.compressedTexSubImage3D(a,b,c,d,e,f,g,h,l,q,x):U.compressedTexSubImage3D(a,b,c,d,e,f,g,h,l,r,x,q)},$a:(a,b,c,d,e)=>U.copyBufferSubData(a,b,c,d,e),Yb:()=>{var a=sd(V),b=U.createProgram();b.name=a;b.ld=b.jd=b.kd=0;b.Fd=1;V[a]=b;return a},yb:a=>{var b=sd(W);W[b]=U.createShader(a);return b},P:a=>U.cullFace(a),va:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=hd[d];e&&(U.deleteBuffer(e),e.name=0,hd[d]=null,d==U.Od&&
(U.Od=0),d==U.Tc&&(U.Tc=0))}},l:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+c*4>>2],e=jd[d];e&&(U.deleteFramebuffer(e),e.name=0,jd[d]=null)}},x:a=>{if(a){var b=V[a];b?(U.deleteProgram(b),b.name=0,V[a]=null):Y||=1281}},ua:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=kd[d];e&&(U.deleteRenderbuffer(e),e.name=0,kd[d]=null)}},N:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2],e=nd[d];e&&(U.deleteSampler(e),e.name=0,nd[d]=null)}},m:a=>{if(a){var b=W[a];b?(U.deleteShader(b),W[a]=null):Y||=1281}},S:(a,b)=>{for(var c=
0;c<a;c++){var d=t[b+c*4>>2],e=ld[d];e&&(U.deleteTexture(e),e.name=0,ld[d]=null)}},Ua:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+c*4>>2];U.deleteVertexArray(md[d]);md[d]=null}},O:a=>U.depthFunc(a),w:a=>{U.depthMask(!!a)},Ra:(a,b)=>U.depthRange(a,b),R:(a,b)=>{U.detachShader(V[a],W[b])},h:a=>U.disable(a),Ca:a=>{U.disableVertexAttribArray(a)},Ka:(a,b,c)=>{U.drawArrays(a,b,c)},La:(a,b,c,d)=>{U.drawArraysInstanced(a,b,c,d)},M:(a,b)=>{for(var c=Od[a],d=0;d<a;d++)c[d]=t[b+d*4>>2];U.drawBuffers(c)},Ma:(a,b,c,
d)=>{U.drawElements(a,b,c,d)},Na:(a,b,c,d,e)=>{U.drawElementsInstanced(a,b,c,d,e)},g:a=>U.enable(a),Ga:a=>{U.enableVertexAttribArray(a)},o:(a,b,c,d)=>{U.framebufferRenderbuffer(a,b,c,kd[d])},d:(a,b,c,d,e)=>{U.framebufferTexture2D(a,b,c,ld[d],e)},n:(a,b,c,d,e)=>{U.framebufferTextureLayer(a,b,ld[c],d,e)},fb:a=>U.frontFace(a),cb:(a,b)=>{td(a,b,"createBuffer",hd)},t:(a,b)=>{td(a,b,"createFramebuffer",jd)},Ya:(a,b)=>{td(a,b,"createRenderbuffer",kd)},_a:(a,b)=>{td(a,b,"createSampler",nd)},Wa:(a,b)=>{td(a,
b,"createTexture",ld)},hb:(a,b)=>{td(a,b,"createVertexArray",md)},eb:(a,b)=>Qd(a,b,2),a:(a,b)=>Qd(a,b,0),nb:(a,b,c,d)=>{a=U.getProgramInfoLog(V[a]);a===null&&(a="(unknown error)");b=b>0&&d?z(a,r,d,b):0;c&&(t[c>>2]=b)},T:(a,b,c)=>{if(c)if(a>=gd)Y||=1281;else if(a=V[a],b==35716)a=U.getProgramInfoLog(a),a===null&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(b==35719){if(!a.ld){var d=U.getProgramParameter(a,35718);for(b=0;b<d;++b)a.ld=Math.max(a.ld,U.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.ld}else if(b==
35722){if(!a.jd)for(d=U.getProgramParameter(a,35721),b=0;b<d;++b)a.jd=Math.max(a.jd,U.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.jd}else if(b==35381){if(!a.kd)for(d=U.getProgramParameter(a,35382),b=0;b<d;++b)a.kd=Math.max(a.kd,U.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.kd}else t[c>>2]=U.getProgramParameter(a,b);else Y||=1281},mb:(a,b,c,d)=>{a=U.getShaderInfoLog(W[a]);a===null&&(a="(unknown error)");b=b>0&&d?z(a,r,d,b):0;c&&(t[c>>2]=b)},db:a=>{var b=od[a];if(!b){switch(a){case 7939:b=
Bd(Pd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=U.getParameter(a))||(Y||=1280);b=b?Bd(b):0;break;case 7938:b=Bd(`OpenGL ES 3.0 (${U.getParameter(7938)})`);break;case 35724:b=U.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Bd(b);break;default:Y||=1280}od[a]=b}return b},e:(a,b)=>{if(Z.version<2)return Y||=1282,0;var c=pd[a];if(c)return b<0||b>=c.length?(Y||=1281,0):
c[b];switch(a){case 7939:return c=Pd().map(Bd),c=pd[a]=c,b<0||b>=c.length?(Y||=1281,0):c[b];default:return Y||=1280,0}},lb:(a,b)=>U.getUniformBlockIndex(V[a],b?y(r,b):""),jb:(a,b)=>{b=b?y(r,b):"";if(a=V[a]){var c=a,d=c.cd,e=c.be,f;if(!d){c.cd=d={};c.ae={};var g=U.getProgramParameter(c,35718);for(f=0;f<g;++f){var h=U.getActiveUniform(c,f);var l=h.name;h=h.size;var q=Rd(l);q=q>0?l.slice(0,q):l;var x=c.Fd;c.Fd+=h;e[q]=[h,x];for(l=0;l<h;++l)d[x]=l,c.ae[x++]=q}}c=a.cd;d=0;f=b;e=Rd(b);e>0&&(d=b.slice(e+
1),d=parseInt(d)>>>0,f=b.slice(0,e));if((e=a.be[f])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else Y||=1281;return-1},xa:(a,b,c)=>{for(var d=Od[b],e=0;e<b;e++)d[e]=t[c+e*4>>2];U.invalidateFramebuffer(a,d)},Jb:a=>{a=V[a];U.linkProgram(a);a.cd=0;a.be={}},u:(a,b)=>{a==3317?qd=b:a==3314&&(rd=b);U.pixelStorei(a,b)},Ha:(a,b)=>U.polygonOffset(a,b),ya:a=>U.readBuffer(a),Xa:(a,b,c,d,e)=>U.renderbufferStorageMultisample(a,b,c,d,e),Za:(a,b,c)=>{U.samplerParameterf(nd[a],b,c)},i:(a,b,c)=>
{U.samplerParameteri(nd[a],b,c)},Oa:(a,b,c,d)=>U.scissor(a,b,c,d),pb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=u[c+f*4>>2])?y(r,g,d?u[d+f*4>>2]:void 0):"";e+=g}U.shaderSource(W[a],e)},A:(a,b,c,d)=>U.stencilFuncSeparate(a,b,c,d),D:a=>U.stencilMask(a),z:(a,b,c,d)=>U.stencilOpSeparate(a,b,c,d),Ta:(a,b,c,d,e)=>U.texStorage2D(a,b,c,d,e),Va:(a,b,c,d,e,f)=>U.texStorage3D(a,b,c,d,e,f),J:(a,b,c,d,e,f,g,h,l)=>{if(U.Tc)U.texSubImage2D(a,b,c,d,e,f,g,h,l);else if(l){var q=Sd(h);U.texSubImage2D(a,b,c,d,e,
f,g,h,q,l>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else{if(l){q=Sd(h);var x=f*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT*(rd||e)+qd-1&-qd);l=q.subarray(l>>>31-Math.clz32(q.BYTES_PER_ELEMENT),l+x>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else l=null;U.texSubImage2D(a,b,c,d,e,f,g,h,l)}},I:(a,b,c,d,e,f,g,h,l,q,x)=>{if(U.Tc)U.texSubImage3D(a,b,c,d,e,f,g,h,l,q,x);else if(x){var B=Sd(q);U.texSubImage3D(a,b,c,d,e,f,g,h,l,q,B,x>>>31-Math.clz32(B.BYTES_PER_ELEMENT))}else U.texSubImage3D(a,
b,c,d,e,f,g,h,l,q,null)},ib:(a,b)=>{var c=U,d=c.uniform1i;var e=U.ce;if(e){var f=e.cd[a];typeof f=="number"&&(e.cd[a]=f=U.getUniformLocation(e,e.ae[a]+(f>0?`[${f}]`:"")));a=f}else Y||=1282,a=void 0;d.call(c,a,b)},kb:(a,b,c)=>{a=V[a];U.uniformBlockBinding(a,b,c)},Q:a=>{a=V[a];U.useProgram(a);U.ce=a},Fa:(a,b)=>{U.vertexAttribDivisor(a,b)},Ea:(a,b,c,d,e)=>{U.vertexAttribIPointer(a,b,c,d,e)},Da:(a,b,c,d,e,f)=>{U.vertexAttribPointer(a,b,c,!!d,e,f)},Sa:(a,b,c,d)=>U.viewport(a,b,c,d),Hb:(a,b)=>La(r.subarray(a,
a+b))};function Xd(a=[]){var b=Ud;a.unshift(fa);var c=a.length,d=Fc((c+1)*4),e=d,f;for(f of a)u[e>>2]=Gc(f),e+=4;u[e>>2]=0;try{var g=b(c,d);qa=g;kc(g)}catch(h){lc(h)}}
function Yd(a=ea){function b(){k.calledRun=!0;if(!pa){M.root=ub(M,null);if(!k.noFSInit&&!hb){var c,d;hb=!0;c??=k.stdin;d??=k.stdout;e??=k.stderr;c?K("stdin",c):xb("/dev/tty","/dev/stdin");d?K("stdout",null,d):xb("/dev/tty","/dev/stdout");e?K("stderr",null,e):xb("/dev/tty1","/dev/stderr");Ab("/dev/stdin",0);Ab("/dev/stdout",1);Ab("/dev/stderr",1)}Zd.hc();ib=!1;k.onRuntimeInitialized?.();k.noInitialRun||Xd(a);if(k.postRun)for(typeof k.postRun=="function"&&(k.postRun=[k.postRun]);k.postRun.length;){var e=
k.postRun.shift();Ca.push(e)}Ba(Ca)}}if(Fa>0)Ga=Yd;else{if(k.preRun)for(typeof k.preRun=="function"&&(k.preRun=[k.preRun]);k.preRun.length;)Ea();Ba(Da);Fa>0?Ga=Yd:k.setStatus?(k.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>k.setStatus(""),1);b()},1)):b()}}var Zd;
(async function(){function a(c){c=Zd=c.exports;Ud=k._main=c.jc;Vd=c.kc;T=c.lc;Jb=c.mc;Rb=c.nc;Ic=c.oc;Fc=c.pc;Hc=c.qc;sa=c.gc;Oc=c.ic;ra();Fa--;k.monitorRunDependencies?.(Fa);Fa==0&&Ga&&(c=Ga,Ga=null,c());return Zd}Fa++;k.monitorRunDependencies?.(Fa);var b={a:Wd};if(k.instantiateWasm)return new Promise(c=>{k.instantiateWasm(b,(d,e)=>{c(a(d,e))})});wa??=k.locateFile?k.locateFile("Tileon_Editor.wasm",ja):ja+"Tileon_Editor.wasm";return function(c){return a(c.instance)}(await za(b))})();Yd();
