var l;l||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",fa=[],ha="./this.program",ia=(a,b)=>{throw b;},ja=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ja=__filename:ba&&(ja=self.location.href);var ka="",la,ma;
if(ca){var fs=require("node:fs");ka=__dirname+"/";ma=a=>{a=pa(a)?new URL(a):a;return fs.readFileSync(a)};la=async a=>{a=pa(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(ha=process.argv[1].replace(/\\/g,"/"));fa=process.argv.slice(2);typeof module!="undefined"&&(module.exports=l);ia=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ka=(new URL(".",ja)).href}catch{}ba&&(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
la=async a=>{if(pa(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ra=console.log.bind(console),sa=console.error.bind(console),ta,ua=!1,wa,pa=a=>a.startsWith("file://");
function xa(){var a=ya.buffer;m=new Int8Array(a);n=new Int16Array(a);p=new Uint8Array(a);Aa=new Uint16Array(a);r=new Int32Array(a);t=new Uint32Array(a);Ba=new Float32Array(a);u=new Float64Array(a);w=new BigInt64Array(a);new BigUint64Array(a)}function Ca(a){l.onAbort?.(a);a=`Aborted(${a})`;sa(a);ua=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Da;
async function Ea(a){if(!ta)try{var b=await la(a);return new Uint8Array(b)}catch{}if(a==Da&&ta)a=new Uint8Array(ta);else if(ma)a=ma(a);else throw"both async and sync fetching of the wasm failed";return a}async function Fa(a,b){try{var c=await Ea(a);return await WebAssembly.instantiate(c,b)}catch(d){sa(`failed to asynchronously prepare wasm: ${d}`),Ca(d)}}
async function Ga(a){var b=Da;if(!ta&&!pa(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){sa(`wasm streaming compile failed: ${d}`),sa("falling back to ArrayBuffer instantiation")}return Fa(b,a)}class Ha{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var n,r,w,m,Ba,u,Aa,t,p,Ia=a=>{for(;a.length>0;)a.shift()(l)},Ja=[],Ka=[],La=()=>{var a=l.preRun.shift();Ka.push(a)},Ma=0,Na=null,Oa=()=>{Ma--;l.monitorRunDependencies?.(Ma);if(Ma==0&&Na){var a=Na;Na=null;a()}},Pa=()=>{Ma++;l.monitorRunDependencies?.(Ma)},Qa=!0;class Ra{constructor(a){this.ud=a-24}init(a,b){t[this.ud+16>>2]=0;t[this.ud+4>>2]=a;t[this.ud+8>>2]=b}}
var Sa=0,Ta=()=>{if(ca){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>(crypto.getRandomValues(b),0)},Ua=a=>(Ua=Ta())(a),Va=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Wa=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=Va(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Xa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ya=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Za=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=Va(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},$a=globalThis.TextDecoder&&new TextDecoder,x=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&$a)return $a.decode(a.subarray(b,
d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},ab=[],bb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},A=(a,b,c,d)=>{if(!(d>0))return 0;var e=
c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(c>=d)break;b[c++]=g}else if(g<=2047){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(g<=65535){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},cb=[];function db(a,b){cb[a]={input:[],output:[],Pc:b};eb(a,fb)}
var fb={open(a){var b=cb[a.node.rdev];if(!b)throw new B(43);a.tty=b;a.seekable=!1},close(a){a.tty.Pc.fsync(a.tty)},fsync(a){a.tty.Pc.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Pc.Wd)throw new B(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Pc.Wd(a.tty)}catch(h){throw new B(29);}if(g===void 0&&e===0)throw new B(6);if(g===null||g===void 0)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Pc.Cd)throw new B(60);try{for(var e=0;e<d;e++)a.tty.Pc.Cd(a.tty,b[c+e])}catch(f){throw new B(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},gb={Wd(){a:{if(!ab.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}c>0&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}b=Array(bb(a)+1);a=A(a,b,0,b.length);b.length=a;ab=b}a=ab.shift()}return a},Cd(a,b){b===null||b===10?(ra(x(a.output)),a.output=
[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(ra(x(a.output)),a.output=[])},oe(){return{Fe:25856,He:5,Ee:191,Ge:35387,De:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},pe(){return 0},qe(){return[24,80]}},hb={Cd(a,b){b===null||b===10?(sa(x(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(sa(x(a.output)),a.output=[])}},D={Lc:null,Kc(){return D.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===
4096)throw new B(63);D.Lc||(D.Lc={dir:{node:{Fc:D.vc.Fc,Rc:D.vc.Rc,lookup:D.vc.lookup,qd:D.vc.qd,rename:D.vc.rename,unlink:D.vc.unlink,rmdir:D.vc.rmdir,readdir:D.vc.readdir,symlink:D.vc.symlink},stream:{Jc:D.wc.Jc}},file:{node:{Fc:D.vc.Fc,Rc:D.vc.Rc},stream:{Jc:D.wc.Jc,read:D.wc.read,write:D.wc.write,Zd:D.wc.Zd,ae:D.wc.ae}},link:{node:{Fc:D.vc.Fc,Rc:D.vc.Rc,readlink:D.vc.readlink},stream:{}},Pd:{node:{Fc:D.vc.Fc,Rc:D.vc.Rc},stream:ib}});c=jb(a,b,c,d);E(c.mode)?(c.vc=D.Lc.dir.node,c.wc=D.Lc.dir.stream,
c.yc={}):(c.mode&61440)===32768?(c.vc=D.Lc.file.node,c.wc=D.Lc.file.stream,c.Dc=0,c.yc=D.ie??(D.ie=new Uint8Array(0))):(c.mode&61440)===40960?(c.vc=D.Lc.link.node,c.wc=D.Lc.link.stream):(c.mode&61440)===8192&&(c.vc=D.Lc.Pd.node,c.wc=D.Lc.Pd.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.yc[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},vc:{Fc(a){var b={};b.dev=(a.mode&61440)===8192?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;E(a.mode)?b.size=4096:(a.mode&61440)===32768?
b.size=a.Dc:(a.mode&61440)===40960?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Rc(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.Dc!=b&&(c=a.yc,a.yc=new Uint8Array(b),a.yc.set(c.subarray(0,Math.min(b,a.Dc))),a.Dc=b))},lookup(){D.wd||(D.wd=new B(44),D.wd.stack="<generic error, no stack>");throw D.wd;},qd(a,b,c,d){return D.createNode(a,
b,c,d)},rename(a,b,c){try{var d=kb(b,c)}catch(f){}if(d){if(E(a.mode))for(var e in d.yc)throw new B(55);lb(d)}delete a.parent.yc[a.name];b.yc[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.yc[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=kb(a,b),d;for(d in c.yc)throw new B(55);delete a.yc[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.yc)]},symlink(a,b,c){a=D.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if((a.mode&
61440)!==40960)throw new B(28);return a.link}},wc:{read(a,b,c,d,e){if(e>=a.node.Dc)return 0;d=Math.min(a.node.Dc-e,d);b.set(a.node.yc.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===m.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(f)a.yc=b.subarray(c,c+d),a.Dc=d;else if(a.Dc===0&&e===0)a.yc=b.slice(c,c+d),a.Dc=d;else{f=e+d;var g=a.yc.length;g>=f||(f=Math.max(f,g*(g<1048576?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.yc.subarray(0,a.Dc),a.yc=new Uint8Array(f),a.yc.set(g));
a.yc.set(b.subarray(c,c+d),e);a.Dc=Math.max(a.Dc,e+d)}return d},Jc(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.Dc);if(b<0)throw new B(28);return b},Zd(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new B(43);a=a.node.yc;if(e&2||a.buffer!==m.buffer){d=!0;Ca();e=void 0;if(!e)throw new B(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);m.set(a,e)}}else d=!1,e=a.byteOffset;return{ud:e,Uc:d}},ae(a,b,c,d){D.wc.write(a,b,0,
d,c,!1);return 0}}},mb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},nb=null,ob={},pb=[],qb=1,rb=null,sb=!1,tb=!0,B=class{name="ErrnoError";constructor(a){this.xc=a}},ub=class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},vb=class{vc={};wc={};Zc=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Kc=a.Kc;this.id=qb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=
this.ctime=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}};
function H(a,b={}){if(!a)throw new B(44);b.yd??(b.yd=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(h=>!!h);for(var d=nb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=Xa(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Wa(e+"/"+a[f]);try{d=kb(d,a[f])}catch(h){if(h?.xc===44&&g&&b.ue)return{path:e};throw h;}!d.Zc||g&&!b.yd||(d=d.Zc.root);if((d.mode&61440)===40960&&(!g||b.gd)){if(!d.vc.readlink)throw new B(52);
d=d.vc.readlink(d);d.charAt(0)==="/"||(d=Xa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new B(32);}function wb(a){for(var b;;){if(a===a.parent)return a=a.Kc.$d,b?a[a.length-1]!=="/"?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function xb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%rb.length}
function lb(a){var b=xb(a.parent.id,a.name);if(rb[b]===a)rb[b]=a.$c;else for(b=rb[b];b;){if(b.$c===a){b.$c=a.$c;break}b=b.$c}}function kb(a,b){var c=E(a.mode)?(c=yb(a,"x"))?c:a.vc.lookup?0:2:54;if(c)throw new B(c);for(c=rb[xb(a.id,b)];c;c=c.$c){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.vc.lookup(a,b)}function jb(a,b,c,d){a=new vb(a,b,c,d);b=xb(a.parent.id,a.name);a.$c=rb[b];return rb[b]=a}function E(a){return(a&61440)===16384}
function yb(a,b){return tb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function zb(a,b){if(!E(a.mode))return 54;try{return kb(a,b),20}catch(c){}return yb(a,"wx")}function Ab(a,b,c){try{var d=kb(a,b)}catch(e){return e.xc}if(a=yb(a,"wx"))return a;if(c){if(!E(d.mode))return 54;if(d===d.parent||wb(d)==="/")return 10}else if(E(d.mode))return 31;return 0}function Bb(a,b){if(!a)throw new B(b);return a}
function I(a){a=pb[a];if(!a)throw new B(8);return a}function Cb(a,b=-1){a=Object.assign(new ub,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!pb[b])break a;throw new B(33);}a.fd=b;return pb[b]=a}function Db(a,b=-1){a=Cb(a,b);a.wc?.Oe?.(a);return a}function Eb(a,b){var c=void 0,d=c?null:a;c??=a.vc.Rc;Bb(c,63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new B(22);throw e;}}var ib={open(a){a.wc=ob[a.node.rdev].wc;a.wc.open?.(a)},Jc(){throw new B(70);}};function eb(a,b){ob[a]={wc:b}}
function Fb(a,b){var c=b==="/";if(c&&nb)throw new B(10);if(!c&&b){var d=H(b,{yd:!1});b=d.path;d=d.node;if(d.Zc)throw new B(10);if(!E(d.mode))throw new B(54);}b={type:a,Ve:{},$d:b,se:[]};a=a.Kc(b);a.Kc=b;b.root=a;c?nb=a:d&&(d.Zc=b,d.Kc&&d.Kc.se.push(b));return a}function Gb(a,b,c){var d=H(a,{parent:!0}).node;a=Ya(a);if(!a)throw new B(28);if(a==="."||a==="..")throw new B(20);var e=zb(d,a);if(e)throw new B(e);if(!d.vc.qd)throw new B(63);return d.vc.qd(d,a,b,c)}
function J(a,b=511){return Gb(a,b&1023|16384,0)}function Hb(a,b,c){typeof c=="undefined"&&(c=b,b=438);Gb(a,b|8192,c)}function Ib(a,b){if(!Za(a))throw new B(44);var c=H(b,{parent:!0}).node;if(!c)throw new B(44);b=Ya(b);var d=zb(c,b);if(d)throw new B(d);if(!c.vc.symlink)throw new B(63);c.vc.symlink(c,b,a)}function Jb(a){var b=H(a,{parent:!0}).node;a=Ya(a);var c=kb(b,a),d=Ab(b,a,!0);if(d)throw new B(d);if(!b.vc.rmdir)throw new B(63);if(c.Zc)throw new B(10);b.vc.rmdir(b,a);lb(c)}
function Kb(a,b){a=H(a,{gd:!b}).node;return Bb(a.vc.Fc,63)(a)}
function Lb(a,b,c=438){if(a==="")throw new B(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var f=H(a,{gd:!(b&131072),ue:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new B(20);}else{if(e)throw new B(31);d=Gb(a,c|511,0);f=!0}if(!d)throw new B(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&!E(d.mode))throw new B(54);
if(!f&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=E(d.mode)&&(e!=="r"||b&576)?31:yb(d,e)):e=44,e))throw new B(e);if(b&512&&!f){e=d;e=typeof e=="string"?H(e,{gd:!0}).node:e;if(E(e.mode))throw new B(31);if((e.mode&61440)!==32768)throw new B(28);if(a=yb(e,"w"))throw new B(a);Eb(e,{size:0,timestamp:Date.now()})}b=Cb({node:d,path:wb(d),flags:b&-131713,seekable:!0,position:0,wc:d.wc,ye:[],error:!1});b.wc.open&&b.wc.open(b);f&&(c&=511,d=typeof d=="string"?H(d,{gd:!0}).node:d,
Eb(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),Ne:void 0}));return b}function Mb(a,b,c){if(a.fd===null)throw new B(8);if(!a.seekable||!a.wc.Jc)throw new B(70);if(c!=0&&c!=1&&c!=2)throw new B(28);a.position=a.wc.Jc(a,b,c);a.ye=[];return a.position}
function Nb(a,b,c,d){var e=m;if(c<0||d<0)throw new B(28);if(a.fd===null)throw new B(8);if((a.flags&2097155)===0)throw new B(8);if(E(a.node.mode))throw new B(31);if(!a.wc.write)throw new B(28);a.seekable&&a.flags&1024&&Mb(a,0,2);var f=typeof d!="undefined";if(!f)d=a.position;else if(!a.seekable)throw new B(70);b=a.wc.write(a,e,b,c,d,void 0);f||(a.position+=b);return b}
function Ob(a,b,c){a=Wa("/dev/"+a);var d=mb(!!b,!!c);Ob.Yd??(Ob.Yd=64);var e=Ob.Yd++<<8|0;eb(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,h,k){for(var q=0,y=0;y<k;y++){try{var z=b()}catch(F){throw new B(29);}if(z===void 0&&q===0)throw new B(6);if(z===null||z===void 0)break;q++;g[h+y]=z}q&&(f.node.atime=Date.now());return q},write(f,g,h,k){for(var q=0;q<k;q++)try{c(g[h+q])}catch(y){throw new B(29);}k&&(f.node.mtime=f.node.ctime=Date.now());return q}});Hb(a,d,e)}var L={};
function Pb(a,b){if(a.type===1&&a.Ac)throw new B(53);var c=a.ad.shift();if(!c){if(a.type===1){a=a.Qc[a.Gc+":"+a.Hc];if(!a)throw new B(53);if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null}throw new B(6);}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,f=c.data.buffer||c.data;b=Math.min(b,d);var g={buffer:new Uint8Array(f,e,b),zc:c.zc,port:c.port};a.type===1&&b<d&&(c.data=new Uint8Array(f,e+b,d-b),a.ad.unshift(c));return g}
function Qb(a,b,c,d,e,f){if(a.type===2){if(e===void 0||f===void 0)e=a.Gc,f=a.Hc;if(e===void 0||f===void 0)throw new B(17);}else e=a.Gc,f=a.Hc;var g=a.Qc[e+":"+f];if(a.type===1&&(!g||g.socket.readyState===g.socket.CLOSING||g.socket.readyState===g.socket.CLOSED))throw new B(53);ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);if(!g||g.socket.readyState!==g.socket.OPEN)return a.type===2&&(g&&g.socket.readyState!==g.socket.CLOSING&&g.socket.readyState!==g.socket.CLOSED||(g=Rb(a,e,
f))),g.sd.push(b),d;try{return g.socket.send(b),d}catch(h){throw new B(28);}}
function Sb(a,b){function c(){a.Qd=!1;M.emit("open",a.stream.fd);try{for(var f=b.sd.shift();f;)b.socket.send(f),f=b.sd.shift()}catch(g){b.socket.close()}}function d(f){if(typeof f=="string")f=(new TextEncoder).encode(f);else{if(f.byteLength==0)return;f=new Uint8Array(f)}var g=e;e=!1;g&&f.length===10&&f[0]===255&&f[1]===255&&f[2]===255&&f[3]===255&&f[4]===112&&f[5]===111&&f[6]===114&&f[7]===116?(f=f[8]<<8|f[9],delete a.Qc[b.zc+":"+b.port],b.port=f,a.Qc[b.zc+":"+b.port]=b):(a.ad.push({zc:b.zc,port:b.port,
data:f}),M.emit("message",a.stream.fd))}var e=!0;ca?(b.socket.on("open",c),b.socket.on("message",(f,g)=>{g&&d((new Uint8Array(f)).buffer)}),b.socket.on("close",()=>M.emit("close",a.stream.fd)),b.socket.on("error",()=>{a.error=14;M.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})):(b.socket.onopen=c,b.socket.onclose=()=>M.emit("close",a.stream.fd),b.socket.onmessage=f=>d(f.data),b.socket.onerror=()=>{a.error=14;M.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})}
function Rb(a,b,c){if(typeof b=="object"){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e="ws://".replace("#","//"),f="binary",g=void 0;M.dd.url&&(e=M.dd.url);M.dd.subprotocol?f=M.dd.subprotocol:M.dd.subprotocol===null&&(f="null");if(e==="ws://"||e==="wss://"){var h=b.split("/");e=e+h[0]+":"+c+"/"+
h.slice(1).join("/")}f!=="null"&&(g=f=f.replace(/^ +| +$/g,"").split(/ *, */));d=new (ca?require("ws"):WebSocket)(e,g);d.binaryType="arraybuffer"}catch(k){throw new B(23);}b={zc:b,port:c,socket:d,sd:[]};a.Qc[b.zc+":"+b.port]=b;Sb(a,b);a.type===2&&typeof a.cd!="undefined"&&b.sd.push(new Uint8Array([255,255,255,255,112,111,114,116,(a.cd&65280)>>8,a.cd&255]));return b}
var M={dd:{},Nd:{},on(a,b){M.Nd[a]=b},emit(a,b){M.Nd[a]?.(b)},Kc(){M.dd=l.websocket||{};var a;((a=l).websocket??(a.websocket={})).on=M.on;return jb(null,"/",16895,0)},createSocket(a,b,c){if(a!=2)throw new B(5);b&=-526337;if(b!=1&&b!=2)throw new B(28);if(b==1&&c&&c!=6)throw new B(66);a={family:a,type:b,protocol:c,Ac:null,error:null,Qc:{},pending:[],ad:[],Wc:M.Ae};b=M.td();c=jb(M.root,b,49152,0);c.bd=a;b=Cb({path:b,node:c,flags:2,seekable:!1,wc:M.wc});a.stream=b;return a},wc:{ce(a){a=a.node.bd;return a.Wc.ce(a)},
md(a,b,c){a=a.node.bd;return a.Wc.md(a,b,c)},read(a,b,c,d){a=Pb(a.node.bd,d);if(!a)return 0;b.set(a.buffer,c);return a.buffer.length},write(a,b,c,d){return Qb(a.node.bd,b,c,d)},close(a){a=a.node.bd;a.Wc.close(a)}},td(){M.td.current||(M.td.current=0);return`socket[${M.td.current++}]`},Ae:{ce(a){if(a.type===1&&a.Ac)return a.pending.length?65:0;var b=0,c=a.type===1?a.Qc[a.Gc+":"+a.Hc]:null;if(a.ad.length||!c||c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=65;if(!c||
c&&c.socket.readyState===c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b=a.Qd?b|4:b|16;return b},md(a,b,c){switch(b){case 21531:return b=0,a.ad.length&&(b=a.ad[0].data.length),r[c>>2]=b,0;case 21537:return a.stream.flags=r[c>>2]?a.stream.flags|2048:a.stream.flags&-2049,0;default:return 28}},close(a){if(a.Ac){try{a.Ac.close()}catch(c){}a.Ac=null}for(var b of Object.values(a.Qc)){try{b.socket.close()}catch(c){}delete a.Qc[b.zc+":"+b.port]}return 0},
bind(a,b,c){if(typeof a.Dd!="undefined"||typeof a.cd!="undefined")throw new B(28);a.Dd=b;a.cd=c;if(a.type===2){a.Ac&&(a.Ac.close(),a.Ac=null);try{a.Wc.listen(a,0)}catch(d){if(d.name!=="ErrnoError")throw d;if(d.xc!==138)throw d;}}},connect(a,b,c){if(a.Ac)throw new B(138);if(typeof a.Gc!="undefined"&&typeof a.Hc!="undefined"){var d=a.Qc[a.Gc+":"+a.Hc];if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new B(7);throw new B(30);}}b=Rb(a,b,c);a.Gc=b.zc;a.Hc=b.port;a.Qd=!0},listen(a){if(!ca)throw new B(138);
if(a.Ac)throw new B(28);var b=require("ws").Server;a.Ac=new b({host:a.Dd,port:a.cd});M.emit("listen",a.stream.fd);a.Ac.on("connection",c=>{if(a.type===1){var d=M.createSocket(a.family,a.type,a.protocol);c=Rb(d,c);d.Gc=c.zc;d.Hc=c.port;a.pending.push(d);M.emit("connection",d.stream.fd)}else Rb(a,c),M.emit("connection",a.stream.fd)});a.Ac.on("close",()=>{M.emit("close",a.stream.fd);a.Ac=null});a.Ac.on("error",()=>{a.error=23;M.emit("error",[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},
accept(a){if(!a.Ac||!a.pending.length)throw new B(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Se(a,b){if(b){if(a.Gc===void 0||a.Hc===void 0)throw new B(53);b=a.Gc;a=a.Hc}else b=a.Dd||0,a=a.cd||0;return{zc:b,port:a}}}},Tb=a=>{a=(a=pb[a])&&(a.node.mode&49152)===49152?a.node.bd:null;if(!a)throw new B(8);return a},Ub=a=>{a=a.split(".");for(var b=0;b<4;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},Wb=a=>{var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;
if(a==="::")return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");a.indexOf(".")>0?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=Number(a[a.length-4])+Number(a[a.length-3])*256,a[a.length-3]=Number(a[a.length-2])+Number(a[a.length-1])*256,a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if(typeof a[b]=="string")if(a[b]==="Z"){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=Vb(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<
16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},Xb=(a,b,c,d,e)=>{switch(b){case 2:c=Ub(c);p.fill(0,a,a+16);e&&(r[e>>2]=16);n[a>>1]=b;r[a+4>>2]=c;n[a+2>>1]=Vb(d);break;case 10:c=Wb(c),p.fill(0,a,a+28),e&&(r[e>>2]=28),r[a>>2]=b,r[a+8>>2]=c[0],r[a+12>>2]=c[1],r[a+16>>2]=c[2],r[a+20>>2]=c[3],n[a+2>>1]=Vb(d)}},Yb=1,Zb={},$b={};function ac(a){var b=Ub(a);if(b!==null)return a;b=Wb(a);if(b!==null)return a;Zb[a]?b=Zb[a]:(b=Yb++,b="172.29."+(b&255)+"."+(b&65280),$b[b]=a,Zb[a]=b);return b}
var bc=a=>(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255),dc=(a,b)=>{var c=n[a>>1],d=cc(Aa[a+2>>1]);switch(c){case 2:if(b!==16)return{xc:28};var e=r[a+4>>2];e=bc(e);break;case 10:if(b!==28)return{xc:28};e=[r[a+8>>2],r[a+12>>2],r[a+16>>2],r[a+20>>2]];a:{a="";var f,g=b=0,h=0,k=0;e=[e[0]&65535,e[0]>>16,e[1]&65535,e[1]>>16,e[2]&65535,e[2]>>16,e[3]&65535,e[3]>>16];var q=!0;for(f=0;f<5;f++)if(e[f]!==0){q=!1;break}if(q){f=bc(e[6]|e[7]<<16);if(e[5]===-1){e="::ffff:"+f;break a}if(e[5]===0){f==="0.0.0.0"&&
(f="");f==="0.0.0.1"&&(f="1");e="::"+f;break a}}for(f=0;f<8;f++)e[f]===0&&(f-g>1&&(k=0),g=f,k++),k>b&&(b=k,h=f-b+1);for(f=0;f<8;f++)b>1&&e[f]===0&&f>=h&&f<h+b?f===h&&(a+=":",h===0&&(a+=":")):(a+=Number(cc(e[f]&65535)).toString(16),a+=f<7?":":"");e=a}break;default:return{xc:5}}return{family:c,zc:e,port:d}},ec=(a,b)=>{a=dc(a,b);if(a.xc)throw new B(a.xc);b=a.zc;a.zc=($b[b]?$b[b]:null)||a.zc;return a},hc=()=>{var a=r[+fc>>2];fc+=4;return a},ic=(a,b)=>a?x(p,a,b):"";
function jc(a,b,c){if(b.charAt(0)==="/")return b;a=a===-100?"/":I(a).path;if(b.length==0){if(!c)throw new B(44);return a}return a+"/"+b}
function kc(a,b){t[a>>2]=b.dev;t[a+4>>2]=b.mode;t[a+8>>2]=b.nlink;t[a+12>>2]=b.uid;t[a+16>>2]=b.gid;t[a+20>>2]=b.rdev;w[a+24>>3]=BigInt(b.size);r[a+32>>2]=4096;r[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();w[a+40>>3]=BigInt(Math.floor(c/1E3));t[a+48>>2]=c%1E3*1E3*1E3;w[a+56>>3]=BigInt(Math.floor(d/1E3));t[a+64>>2]=d%1E3*1E3*1E3;w[a+72>>3]=BigInt(Math.floor(e/1E3));t[a+80>>2]=e%1E3*1E3*1E3;w[a+88>>3]=BigInt(b.ino);return 0}
var fc=void 0,lc=[0,31,60,91,121,152,182,213,244,274,305,335],mc=[0,31,59,90,120,151,181,212,243,273,304,334],nc=[],oc=(a,b)=>{nc.length=0;for(var c;c=p[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;nc.push(c==112?t[b>>2]:c==106?w[b>>3]:c==105?r[b>>2]:u[b>>3]);b+=d?8:4}return nc},yc=(a,b)=>{pc=a;qc=b;if(rc)if(sc||=!0,a==0)tc=function(){setTimeout(uc,Math.max(0,vc+b-performance.now())|0)};else if(a==1)tc=function(){wc(uc)};else{if(!xc)if(globalThis.scheduler)xc=scheduler.postTask.bind(scheduler);else if(globalThis.setImmediate)xc=
setImmediate;else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);xc=d=>{c.push(d);ba?postMessage("setimmediate"):postMessage("setimmediate","*")}}tc=function(){xc(uc)}}},zc=a=>{wa=a;Qa||(l.onExit?.(a),ua=!0);ia(a,new Ha(a))},Ac=a=>{a instanceof Ha||a=="unwind"||ia(1,a)},Bc=()=>{if(!Qa)try{var a=wa;wa=a;zc(a)}catch(b){Ac(b)}},Lc=(a,b,c,d,e)=>{function f(){return g<Cc?(Bc(),!1):!0}rc=a;Dc=d;var g=Cc;sc=!1;uc=function(){if(!ua)if(Ec.length>0){var h=
Ec.shift();h.Qe(h.Be);if(Fc){var k=Fc,q=k%1==0?k-1:Math.floor(k);Fc=h.Je?q:(8*k+(q+.5))/9}l.setStatus&&(h=l.statusMessage||"Please wait...",k=Fc??0,q=Gc.Pe??0,k?k<q?l.setStatus("{message} ({expected - remaining}/{expected})"):l.setStatus(h):l.setStatus(""));f()&&setTimeout(uc,0)}else if(f())if(Hc=Hc+1|0,pc==1&&qc>1&&Hc%qc!=0)tc();else{pc==0&&(vc=performance.now());a:if(!ua){for(h of Ic)if(h()===!1)break a;Jc(a);for(k of Kc)k()}f()&&tc()}};e||(b>0?yc(0,1E3/b):yc(1,1),tc());if(c)throw"unwind";},Jc=
a=>{if(!ua)try{a()}catch(b){Ac(b)}finally{Bc()}},sc=!1,tc=null,Cc=0,rc=null,Dc=0,pc=0,qc=0,Hc=0,Ec=[],Ic=[],Kc=[];function Mc(){tc=null;Cc++}var Nc=0;function wc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(Nc===0)Nc=b+1E3/60;else for(;b+2>=Nc;)Nc+=1E3/60;setTimeout(a,Math.max(Nc-b,0))}}var Gc={},vc,uc,xc,Fc;function Oc(a){var b=N.Bc[a];b.target.removeEventListener(b.Cc,b.Vd,b.Mc);N.Bc.splice(a,1)}
function Pc(a){function b(e,f){if(e.length!=f.length)return!1;for(var g in e)if(e[g]!=f[g])return!1;return!0}var c=Qc,d;for(d of N.Tc)if(d.Gd==c&&b(d.Md,a))return;N.Tc.push({Gd:c,de:1,Md:a});N.Tc.sort((e,f)=>e.de-f.de)}function Rc(){var a=Qc;N.Tc=N.Tc.filter(b=>b.Gd!=a)}function Sc(){if(navigator.userActivation?navigator.userActivation.isActive:N.ld&&N.Rd.jd){var a=N.Tc;N.Tc=[];for(var b of a)b.Gd(...b.Md)}}
function Tc(a){if(!a.target)return-4;if(a.Ec)a.Vd=function(c){++N.ld;N.Rd=a;Sc();a.Oc(c);Sc();--N.ld},a.target.addEventListener(a.Cc,a.Vd,a.Mc),N.Bc.push(a);else for(var b=0;b<N.Bc.length;++b)N.Bc[b].target==a.target&&N.Bc[b].Cc==a.Cc&&Oc(b--);return 0}function Uc(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var N={Ce:0,Re:0,Ad:0,rd:0,Ld:0,Id:0,xd:0,Le:0,We:0,Ke:0,zd:0,Bd:0,Kd:0,Hd:0,Ye(){for(;N.Bc.length;)Oc(N.Bc.length-1);N.Tc=[]},ld:0,Tc:[],Bc:[],we:(a,b)=>{for(var c=0;c<N.Bc.length;++c)N.Bc[c].target!=a||b&&b!=N.Bc[c].Cc||Oc(c--)},Ze(a){var b=!1;for(let c=0;c<N.Bc.length;++c){let d=N.Bc[c];d.target===a.target&&d.Ic===a.Ic&&d.Ec===a.Ec&&d.Nc===a.Nc&&(Oc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Vc=[0,globalThis.document??0,globalThis.window??
0],O=a=>{a=a>2?a?x(p,a):"":a;return Vc[a]||globalThis.document?.querySelector(a)},Xc=a=>{var b=bb(a)+1,c=Wc(b);A(a,p,c,b);return c},$c=a=>{var b=Yc(),c=Wc(8),d=c+4;a=Xc(a.id);if(a=O(a))r[c>>2]=a.width,r[d>>2]=a.height;c=[r[c>>2],r[d>>2]];Zc(b);return c},ad=(a,b,c)=>{a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},bd=(a,b,c)=>{if(a.Ie){var d=Yc();a=Xc(a.id);ad(a,b,c);Zc(d)}else a.width=b,a.height=c},cd={},dd=[],P=a=>{var b=dd[a];b||(dd[a]=b=ed.get(a));return b},gd=a=>{function b(){fd()||(document.removeEventListener("fullscreenchange",
b),document.removeEventListener("webkitfullscreenchange",b),bd(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=h,k||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=k,a.style.paddingLeft=q,a.style.paddingRight=y,a.style.paddingTop=z,a.style.paddingBottom=F,a.style.marginLeft=K,a.style.marginRight=da,a.style.marginTop=U,a.style.marginBottom=ea,document.body.style.margin=Y,document.documentElement.style.overflow=na,document.body.scroll=oa,a.style.imageRendering=
v,a.ed&&a.ed.Sc.viewport(0,0,d,e),cd.kd&&P(cd.kd)(37,0,cd.Od))}var c=$c(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,h=a.style.backgroundColor,k=document.body.style.backgroundColor,q=a.style.paddingLeft,y=a.style.paddingRight,z=a.style.paddingTop,F=a.style.paddingBottom,K=a.style.marginLeft,da=a.style.marginRight,U=a.style.marginTop,ea=a.style.marginBottom,Y=document.body.style.margin,na=document.documentElement.style.overflow,oa=document.body.scroll,v=a.style.imageRendering;document.addEventListener("fullscreenchange",
b);document.addEventListener("webkitfullscreenchange",b)},hd=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},jd=a=>Vc.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},Qc=(a,b)=>{if(b.Ed!=0||b.vd!=0){gd(a);var c=b.xe?innerWidth:screen.width,d=b.xe?innerHeight:screen.height,e=jd(a),f=e.width;e=e.height;var g=$c(a),h=g[0];g=g[1];b.Ed==3?(hd(a,(d-e)/2,(c-f)/2),c=f,d=e):b.Ed==2&&(c*g<h*d?(f=g*c/h,hd(a,(d-f)/2,0),d=f):(f=h*d/g,hd(a,0,(c-f)/
2),c=f));var k;(k=a.style).backgroundColor||(k.backgroundColor="black");let q;(q=document.body.style).backgroundColor||(q.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";b.me==1&&(a.style.imageRendering="optimizeSpeed",a.style.imageRendering="-moz-crisp-edges",a.style.imageRendering="-o-crisp-edges",a.style.imageRendering="-webkit-optimize-contrast",a.style.imageRendering="optimize-contrast",a.style.imageRendering="crisp-edges",a.style.imageRendering="pixelated");k=b.vd==2?devicePixelRatio:
1;b.vd!=0&&(c=c*k|0,d=d*k|0,bd(a,c,d),a.ed&&a.ed.Sc.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return N.fullscreenEnabled()?-3:-1;cd=b;b.kd&&P(b.kd)(37,0,b.Od);return 0};function fd(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}
var kd=(a,b)=>{if(!N.fullscreenEnabled())return-1;a=O(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?(navigator.userActivation?navigator.userActivation.isActive:N.ld&&N.Rd.jd)?Qc(a,b):b.he?(Pc([a,b]),1):-2:-3:-4},ld=(a,b,c,d,e,f)=>{N.xd||(N.xd=Q(256));a={target:O(a),Cc:f,Ic:e,Nc:b,Ec:d,Oc:g=>{var h=g.target.id??"",k=N.xd;A(Uc(g.target),p,k+0,128);A(h,p,k+128,128);P(d)(e,k,b)&&g.preventDefault()},Mc:c};return Tc(a)},md=(a,b,c,d,e)=>{N.zd||(N.zd=Q(276));return Tc({target:a,Cc:e,Ic:19,Nc:b,
Ec:d,Oc:f=>{var g=N.zd,h=fd(),k=!!h;m[g]=k;m[g+1]=N.fullscreenEnabled();var q=k?h:N.ve,y=q?.id??"";A(Uc(q),p,g+2,128);A(y,p,g+130,128);r[g+260>>2]=q?.clientWidth??0;r[g+264>>2]=q?.clientHeight??0;r[g+268>>2]=screen.width;r[g+272>>2]=screen.height;k&&(N.ve=h);P(d)(19,g,b)&&f.preventDefault()},Mc:c})},nd=(a,b,c,d,e,f)=>{N.Ad||(N.Ad=Q(160));a={target:O(a),Cc:f,Ic:e,Nc:b,Ec:d,Oc:g=>{var h=N.Ad;u[h>>3]=g.timeStamp;var k=h>>2;r[k+2]=g.location;m[h+12]=g.ctrlKey;m[h+13]=g.shiftKey;m[h+14]=g.altKey;m[h+15]=
g.metaKey;m[h+16]=g.repeat;r[k+5]=g.charCode;r[k+6]=g.keyCode;r[k+7]=g.which;A(g.key??"",p,h+32,32);A(g.code??"",p,h+64,32);A(g.char??"",p,h+96,32);A(g.locale??"",p,h+128,32);P(d)(e,h,b)&&g.preventDefault()},Mc:c};return Tc(a)},od=(a,b,c)=>{u[a>>3]=b.timeStamp;var d=a>>2;r[d+2]=b.screenX;r[d+3]=b.screenY;r[d+4]=b.clientX;r[d+5]=b.clientY;m[a+24]=b.ctrlKey;m[a+25]=b.shiftKey;m[a+26]=b.altKey;m[a+27]=b.metaKey;n[d*2+14]=b.button;n[d*2+15]=b.buttons;r[d+8]=b.movementX;r[d+9]=b.movementY;a=jd(c);r[d+
10]=b.clientX-(a.left|0);r[d+11]=b.clientY-(a.top|0)},pd=(a,b,c,d,e,f)=>{N.rd||(N.rd=Q(64));a=O(a);return Tc({target:a,jd:f!="mousemove"&&f!="mouseenter"&&f!="mouseleave",Cc:f,Ic:e,Nc:b,Ec:d,Oc:g=>{od(N.rd,g,a);P(d)(e,N.rd,b)&&g.preventDefault()},Mc:c})},qd=(a,b,c,d)=>{N.Bd||(N.Bd=Q(257));return Tc({target:a,Cc:"pointerlockchange",Ic:20,Nc:b,Ec:d,Oc:e=>{var f=N.Bd,g=document.pointerLockElement;m[f]=!!g;var h=g?.id??"";A(Uc(g),p,f+1,128);A(h,p,f+129,128);P(d)(20,f,b)&&e.preventDefault()},Mc:c})},rd=
(a,b,c,d)=>{N.Id||(N.Id=Q(36));a=O(a);return Tc({target:a,Cc:"resize",Ic:10,Nc:b,Ec:d,Oc:e=>{if(e.target==a){var f=document.body;if(f){var g=N.Id;r[g>>2]=0;r[g+4>>2]=f.clientWidth;r[g+8>>2]=f.clientHeight;r[g+12>>2]=innerWidth;r[g+16>>2]=innerHeight;r[g+20>>2]=outerWidth;r[g+24>>2]=outerHeight;r[g+28>>2]=pageXOffset|0;r[g+32>>2]=pageYOffset|0;P(d)(10,g,b)&&e.preventDefault()}}},Mc:c})},sd=(a,b,c,d,e,f)=>{N.Hd||(N.Hd=Q(1552));a=O(a);return Tc({target:a,jd:f=="touchstart"||f=="touchend",Cc:f,Ic:e,Nc:b,
Ec:d,Oc:g=>{var h={},k=g.touches;for(var q of k)q.Xd=q.be=0,h[q.identifier]=q;for(var y of g.changedTouches)y.Xd=1,h[y.identifier]=y;for(var z of g.targetTouches)h[z.identifier].be=1;k=N.Hd;u[k>>3]=g.timeStamp;m[k+12]=g.ctrlKey;m[k+13]=g.shiftKey;m[k+14]=g.altKey;m[k+15]=g.metaKey;q=k+16;y=jd(a);z=0;for(let F of Object.values(h))if(h=q>>2,r[h]=F.identifier,r[h+1]=F.screenX,r[h+2]=F.screenY,r[h+3]=F.clientX,r[h+4]=F.clientY,r[h+5]=F.pageX,r[h+6]=F.pageY,m[q+28]=F.Xd,m[q+29]=F.be,r[h+8]=F.clientX-(y.left|
0),r[h+9]=F.clientY-(y.top|0),q+=48,++z>31)break;r[k+8>>2]=z;P(d)(e,k,b)&&g.preventDefault()},Mc:c})},td=(a,b,c)=>{var d=Vc[1];N.Kd||(N.Kd=Q(8));return Tc({target:d,Cc:"visibilitychange",Ic:21,Nc:a,Ec:c,Oc:e=>{var f=N.Kd,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);m[f]=document.hidden;r[f+4>>2]=g;P(c)(21,f,a)&&e.preventDefault()},Mc:b})},ud=(a,b,c,d)=>{N.Ld||(N.Ld=Q(96));return Tc({target:a,jd:!0,Cc:"wheel",Ic:9,Nc:b,Ec:d,Oc:e=>{var f=N.Ld;od(f,e,a);u[f+64>>3]=
e.deltaX;u[f+72>>3]=e.deltaY;u[f+80>>3]=e.deltaZ;r[f+88>>2]=e.deltaMode;P(d)(9,f,b)&&e.preventDefault()},Mc:c})};function vd(a,b){var c=a.Xc.pop()??a.Uc.length;a.Uc[c]=b;return c}class wd{Uc=[void 0];Xc=[];get(a){return this.Uc[a]}has(a){return this.Uc[a]!==void 0}}
async function xd(){return new Promise((a,b)=>{try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){return b(d)}c.onupgradeneeded=d=>{d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=d=>a(d.target.result);c.onerror=b})}var R,yd;
function zd(a,b,c,d,e){function f(){var G=0,C=0;v.response&&Y&&t[a+12>>2]===0&&(C=v.response.byteLength);C>0&&(G=Ad(t[a+12>>2],C),p.set(new Uint8Array(v.response),G));t[a+12>>2]=G;S(a+16,C);S(a+24,0);(G=v.response?.byteLength??0)&&S(a+32,G);n[a+40>>1]=v.readyState;n[a+42>>1]=v.status;v.statusText&&A(v.statusText,p,a+44,64);oa&&(G=Bd(v.responseURL),t[a+200>>2]=G)}var g=t[a+8>>2];if(g){var h=g?x(p,g):"",k=a+108,q=ic(k+0);q||="GET";var y=t[k+56>>2],z=t[k+68>>2],F=t[k+72>>2];g=t[k+76>>2];var K=t[k+80>>
2],da=t[k+84>>2],U=t[k+88>>2],ea=t[k+52>>2],Y=!!(ea&1),na=!!(ea&2),oa=!!(ea&64);z=z?z?x(p,z):"":void 0;F=F?F?x(p,F):"":void 0;var v=new XMLHttpRequest;v.withCredentials=!!p[k+60];v.Xc=na;v.open(q,h,!oa,z,F);oa||(v.timeout=y);v.af=h;v.responseType="arraybuffer";K&&(h=K?x(p,K):"",v.overrideMimeType(h));if(g)for(;;){k=t[g>>2];if(!k)break;h=t[g+4>>2];if(!h)break;g+=8;k=k?x(p,k):"";h=h?x(p,h):"";v.setRequestHeader(k,h)}var qa=vd(R,v);t[a>>2]=qa;g=da&&U?p.slice(da,da+U):null;v.onload=G=>{R.has(qa)&&(f(),
v.status>=200&&v.status<300?b(a,v,G):c(a,G))};v.onerror=G=>{R.has(qa)&&(f(),c(a,G))};v.ontimeout=G=>{R.has(qa)&&c(a,G)};v.onprogress=G=>{if(R.has(qa))for(var C=Y&&na?v.response?.byteLength??0:0,va=0;va<C||!C;){var V=Math.min(C-va,8388608),za=0;V>0&&Y&&na&&(za=Ad(t[a+12>>2],V),p.set(new Uint8Array(v.response,va,V),za));t[a+12>>2]=za;S(a+16,V);S(a+24,G.loaded-C+va);S(a+32,G.total);n[a+40>>1]=v.readyState;za=v.status;v.readyState>=3&&v.status===0&&G.loaded>0&&(za=200);n[a+42>>1]=za;v.statusText&&A(v.statusText,
p,a+44,64);d(a,G);va+=V;if(!C)break}};v.onreadystatechange=G=>{if(R.has(qa)){n[a+40>>1]=v.readyState;v.readyState>=2&&(n[a+42>>1]=v.status);if(!oa&&v.readyState===2&&v.responseURL.length>0){var C=Bd(v.responseURL);t[a+200>>2]=C}e(a,G)}};try{v.send(g)}catch(G){c(a,G)}}else c(a,"no url specified!")}var S=(a,b)=>{t[a>>2]=b;t[a+4>>2]=(b-t[a>>2])/4294967296},Bd=a=>{var b=bb(a)+1,c=Q(b);c&&A(a,p,c,b);return c};
function Cd(a,b,c,d){var e=yd;if(e){var f=t[a+108+64>>2];f||=t[a+8>>2];var g=f?x(p,f):"";try{var h=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,g);h.onsuccess=()=>{n[a+40>>1]=4;n[a+42>>1]=200;A("OK",p,a+44,64);c(a,0,g)};h.onerror=k=>{n[a+40>>1]=4;n[a+42>>1]=413;A("Payload Too Large",p,a+44,64);d(a,0,k)}}catch(k){d(a,0,k)}}else d(a,0,"IndexedDB not available!")}
function Dd(a,b,c){var d=yd;if(d){var e=t[a+108+64>>2];e||=t[a+8>>2];e=e?x(p,e):"";try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=g=>{if(g.target.result){g=g.target.result;var h=g.byteLength||g.length,k=Q(h);p.set(new Uint8Array(g),k);t[a+12>>2]=k;S(a+16,h);S(a+24,0);S(a+32,h);n[a+40>>1]=4;n[a+42>>1]=200;A("OK",p,a+44,64);b(a,0,g)}else n[a+40>>1]=4,n[a+42>>1]=404,A("Not Found",p,a+44,64),c(a,0,"no data")};f.onerror=g=>{n[a+40>>1]=4;n[a+42>>1]=404;A("Not Found",
p,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
function Ed(a,b,c){var d=yd;if(d){var e=t[a+108+64>>2];e||=t[a+8>>2];e=e?x(p,e):"";try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=g=>{g=g.target.result;t[a+12>>2]=0;S(a+16,0);S(a+24,0);S(a+32,0);n[a+40>>1]=4;n[a+42>>1]=200;A("OK",p,a+44,64);b(a,0,g)};f.onerror=g=>{n[a+40>>1]=4;n[a+42>>1]=404;A("Not Found",p,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
var T,Fd=a=>{a.Me=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Gd=a=>{a.Te=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Hd=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},Id=1,Jd=[],W=[],Kd=[],Ld=[],Md=[],Nd=[],Od=[],Pd=[],Qd=[],Rd={},Sd={},Td=4,Ud=0,Vd=a=>{for(var b=Id++,c=a.length;c<b;c++)a[c]=null;return b},Wd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=T[c](),g=f&&Vd(d);f?(f.name=g,d[g]=f):X||=1282;r[b+e*4>>2]=g}},Yd=(a,b)=>{a.Xc||(a.Xc=a.getContext,a.getContext=function(d,e){e=a.Xc(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Xd(c,b):0},Xd=
(a,b)=>{var c=Vd(Pd),d={handle:c,attributes:b,version:b.re,Sc:a};a.canvas&&(a.canvas.ed=d);Pd[c]=d;if(typeof b.Ud=="undefined"||b.Ud)if((a=d)||(a=Z),!a.ne){a.ne=!0;b=a.Sc;b.te=b.getExtension("WEBGL_multi_draw");b.le=b.getExtension("EXT_polygon_offset_clamp");b.ke=b.getExtension("EXT_clip_control");b.ze=b.getExtension("WEBGL_polygon_mode");Fd(b);Gd(b);a.version>=2&&(b.Td=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(a.version<2||!b.Td)b.Td=b.getExtension("EXT_disjoint_timer_query");for(var e of Hd(b))e.includes("lose_context")||
e.includes("debug")||b.getExtension(e)}return c},X,Z,Zd=["default","low-power","high-performance"],$d=new wd;function ae(a){return $d.has(a)?$d.get(a):0}function be(a){this.Fd||(this.Fd=Q(520));t[this.Fd>>2]=a;return this.Fd}
var ce={},ee=()=>{if(!de){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ha},b;for(b in ce)ce[b]===void 0?delete a[b]:a[b]=ce[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);de=c}return de},de,fe=(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=t[b>>2],h=t[b+4>>2];b+=8;var k=a;var q=g,y=h,z=d,F=m;if(y<0||z<0)throw new B(28);if(k.fd===null)throw new B(8);if((k.flags&2097155)===1)throw new B(8);if(E(k.node.mode))throw new B(31);
if(!k.wc.read)throw new B(28);g=typeof z!="undefined";if(!g)z=k.position;else if(!k.seekable)throw new B(70);q=k.wc.read(k,F,q,y,z);g||(k.position+=q);k=q;if(k<0)return-1;e+=k;if(k<h)break;typeof d!="undefined"&&(d+=k)}return e},ge=(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=t[b>>2],h=t[b+4>>2];b+=8;g=Nb(a,g,h,d);if(g<0)return-1;e+=g;if(g<h)break;typeof d!="undefined"&&(d+=g)}return e},he=[],ie=()=>{var a=Hd(T);return a=a.concat(a.map(b=>"GL_"+b))},je=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=
1;break;case 36344:c!=0&&c!=1&&(X||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=T.getParameter(34467);d=e?e.length:0;break;case 33309:if(Z.version<2){X||=1282;return}d=ie().length;break;case 33307:case 33308:if(Z.version<2){X||=1280;return}d=a==33307?3:0}if(d===void 0)switch(e=T.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":X||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:X||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+a*4>>2]=e[a];break;case 2:Ba[b+a*4>>2]=e[a];break;case 4:m[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){X||=1280;sa(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:X||=1280;sa(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:S(b,d);break;case 0:r[b>>2]=d;break;case 2:Ba[b>>2]=d;break;case 4:m[b]=d?1:0}}else X||=1281},ke=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),le=a=>{a-=5120;return a==0?m:a==1?p:a==2?n:a==4?r:a==6?Ba:a==5||a==28922||a==28520||a==30779||a==30782?t:Aa};rb=Array(4096);Fb(D,"/");J("/tmp");J("/home");J("/home/web_user");
(function(){J("/dev");eb(259,{read:()=>0,write:(d,e,f,g)=>g,Jc:()=>0});Hb("/dev/null",259);db(1280,gb);db(1536,hb);Hb("/dev/tty",1280);Hb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b===0&&(Ua(a),b=a.byteLength);return a[--b]};Ob("random",c);Ob("urandom",c);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");Fb({Kc(){var b=jb(a,"fd",16895,73);b.wc={Jc:D.wc.Jc};b.vc={lookup(c,d){c=+d;var e=I(c);c={parent:null,Kc:{$d:"fake"},vc:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(pb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();l.requestAnimationFrame=wc;l.pauseMainLoop=Mc;l.resumeMainLoop=function(){Cc++;var a=pc,b=qc,c=rc;rc=null;Lc(c,0,!1,Dc,!0);yc(a,b);tc()};
l.preMainLoop&&Ic.push(l.preMainLoop);l.postMainLoop&&Kc.push(l.postMainLoop);(async function(){R=new wd;Pa();try{yd=await xd()}catch(a){yd=!1}finally{Oa()}})();for(let a=0;a<32;++a)he.push(Array(a));l.noExitRuntime&&(Qa=l.noExitRuntime);l.print&&(ra=l.print);l.printErr&&(sa=l.printErr);l.wasmBinary&&(ta=l.wasmBinary);l.arguments&&(fa=l.arguments);l.thisProgram&&(ha=l.thisProgram);if(l.preInit)for(typeof l.preInit=="function"&&(l.preInit=[l.preInit]);l.preInit.length>0;)l.preInit.shift()();
var me={932136:a=>{try{let b=new (window.AudioContext||window.webkitAudioContext)({sampleRate:a,latencyHint:"interactive"});l.zyWebAudio=b;a=function(){b.resume()};document.addEventListener("click",a,{once:!0});document.addEventListener("keydown",a,{once:!0});document.addEventListener("touchstart",a,{once:!0});return 1}catch(b){return 0}},932610:()=>{l.zyWebAudio.close()},932644:()=>l.zyWebAudio.currentTime,932689:(a,b,c)=>{var d=l.zyWebAudio,e=d.createBuffer(2,b,d.sampleRate),f=e.getChannelData(0),
g=e.getChannelData(1);a>>=2;for(var h=0;h<b;++h)f[h]=Ba[a+h*2],g[h]=Ba[a+h*2+1];b=d.createBufferSource();b.buffer=e;b.connect(d.destination);b.start(c)},933183:()=>{l.zyWebAudio.suspend()},933219:()=>{l.zyWebAudio.resume()},933254:(a,b,c)=>{a=a?x(p,a,b):"";console[["debug","info","warn","error"][c]||"log"](a)},933396:(a,b)=>{document.title=a?x(p,a,b):""},933439:a=>{var b=Vc["!ZyWindowHTML5"];b&&(b.style.display=a?"block":"none")},933565:()=>{var a=Vc["!ZyWindowHTML5"];a&&a.focus()},933661:()=>window.devicePixelRatio||
1,933704:()=>{Vc["!ZyWindowHTML5"]=l.canvas},933762:()=>window.devicePixelRatio||1,933805:()=>window.devicePixelRatio||1,933848:()=>window.matchMedia("(dynamic-range: high)").matches?1:0,933916:()=>location.protocol==="https:"?1:0},ne,oe,Q,Ad,Vb,cc,Zc,Wc,Yc,ya,ed,pe={y:(a,b,c)=>{(new Ra(a)).init(b,c);Sa++;Ca()},vb:function(a,b,c){try{var d=Tb(a),e=d.Wc.accept(d);b&&Xb(b,e.family,ac(e.Gc),e.Hc,c);return e.stream.fd}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;return-f.xc}},ub:function(a,
b,c){try{var d=Tb(a),e=ec(b,c);d.Wc.bind(d,e.zc,e.port);return 0}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;return-f.xc}},f:function(a,b,c){fc=c;try{var d=I(a);switch(b){case 0:var e=hc();if(e<0)break;for(;pb[e];)e++;return Db(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=hc(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=hc(),n[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;return-f.xc}},
Nb:function(a,b){try{var c=I(a),d=c.node,e=c.wc.Fc;a=e?c:d;e??=d.vc.Fc;Bb(e,63);var f=e(a);return kc(b,f)}catch(g){if(typeof L=="undefined"||g.name!=="ErrnoError")throw g;return-g.xc}},Ib:function(a,b){try{if(b===0)return-28;var c=bb("/")+1;if(b<c)return-68;A("/",p,a,b);return c}catch(d){if(typeof L=="undefined"||d.name!=="ErrnoError")throw d;return-d.xc}},zb:function(a,b,c){try{var d=I(a);if(!d.Vc){var e=H(d.path,{gd:!0}).node;var f=Bb(e.vc.readdir,54)(e);d.Vc=f}a=0;var g=Mb(d,0,1),h=Math.floor(g/
280),k=Math.min(d.Vc.length,h+Math.floor(c/280));for(c=h;c<k;c++){var q=d.Vc[c];if(q==="."){var y=d.node.id;var z=4}else if(q==="..")y=H(d.path,{parent:!0}).node.id,z=4;else{try{var F=kb(d.node,q)}catch(K){if(K?.xc===28)continue;throw K;}y=F.id;z=(F.mode&61440)===8192?2:E(F.mode)?4:(F.mode&61440)===40960?10:8}w[b+a>>3]=BigInt(y);w[b+a+8>>3]=BigInt((c+1)*280);n[b+a+16>>1]=280;m[b+a+18]=z;A(q,p,b+a+19,256);a+=280}Mb(d,c*280,0);return a}catch(K){if(typeof L=="undefined"||K.name!=="ErrnoError")throw K;
return-K.xc}},Pb:function(a,b,c){fc=c;try{var d=I(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Pc.oe){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=hc();r[e>>2]=25856;r[e+4>>2]=5;r[e+8>>2]=191;r[e+12>>2]=35387;for(var f=0;f<32;f++)m[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Pc.pe)for(e=hc(),a=[],f=0;f<32;f++)a.push(m[e+f+17]);
return 0;case 21519:if(!d.tty)return-59;e=hc();return r[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=hc();if(!d.wc.md)throw new B(59);return d.wc.md(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Pc.qe&&(f=[24,80],e=hc(),n[e>>1]=f[0],n[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if(typeof L=="undefined"||g.name!=="ErrnoError")throw g;return-g.xc}},tb:function(a,b){try{var c=Tb(a);c.Wc.listen(c,b);return 0}catch(d){if(typeof L==
"undefined"||d.name!=="ErrnoError")throw d;return-d.xc}},Jb:function(a,b){try{return a=a?x(p,a):"",kc(b,Kb(a,!0))}catch(c){if(typeof L=="undefined"||c.name!=="ErrnoError")throw c;return-c.xc}},Fb:function(a,b,c){try{return b=b?x(p,b):"",b=jc(a,b),J(b,c&-19),0}catch(d){if(typeof L=="undefined"||d.name!=="ErrnoError")throw d;return-d.xc}},Kb:function(a,b,c,d){try{b=b?x(p,b):"";var e=d&256;b=jc(a,b,d&4096);return kc(c,e?Kb(b,!0):Kb(b))}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;
return-f.xc}},V:function(a,b,c,d){fc=d;try{b=b?x(p,b):"";b=jc(a,b);var e=d?hc():0;c&64&&(e&=-19);return Lb(b,c,e).fd}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;return-f.xc}},sb:function(a,b,c,d,e,f){try{var g=Tb(a),h=Pb(g,c);if(!h)return 0;e&&Xb(e,g.family,ac(h.zc),h.port,f);p.set(h.buffer,b);return h.buffer.byteLength}catch(k){if(typeof L=="undefined"||k.name!=="ErrnoError")throw k;return-k.xc}},xb:function(a){try{return a=a?x(p,a):"",Jb(a),0}catch(b){if(typeof L=="undefined"||
b.name!=="ErrnoError")throw b;return-b.xc}},rb:function(a,b,c,d,e,f){try{var g=Tb(a);if(!e)return Nb(g.stream,b,c);var h=ec(e,f);return Qb(g,m,b,c,h.zc,h.port)}catch(k){if(typeof L=="undefined"||k.name!=="ErrnoError")throw k;return-k.xc}},pb:function(a,b,c){try{return M.createSocket(a,b,c).stream.fd}catch(d){if(typeof L=="undefined"||d.name!=="ErrnoError")throw d;return-d.xc}},Lb:function(a,b){try{return a=a?x(p,a):"",kc(b,Kb(a))}catch(c){if(typeof L=="undefined"||c.name!=="ErrnoError")throw c;return-c.xc}},
yb:function(a,b,c){try{b=b?x(p,b):"";b=jc(a,b);if(c)if(c===512)Jb(b);else return-28;else{a=b;var d=H(a,{parent:!0}).node;if(!d)throw new B(44);var e=Ya(a),f=kb(d,e),g=Ab(d,e,!1);if(g)throw new B(g);if(!d.vc.unlink)throw new B(63);if(f.Zc)throw new B(10);d.vc.unlink(d,e);lb(f)}return 0}catch(h){if(typeof L=="undefined"||h.name!=="ErrnoError")throw h;return-h.xc}},Ub:()=>Ca(""),Db:function(a,b){a=a<-9007199254740992||a>9007199254740992?NaN:Number(a);a=new Date(a*1E3);r[b>>2]=a.getSeconds();r[b+4>>2]=
a.getMinutes();r[b+8>>2]=a.getHours();r[b+12>>2]=a.getDate();r[b+16>>2]=a.getMonth();r[b+20>>2]=a.getFullYear()-1900;r[b+24>>2]=a.getDay();var c=a.getFullYear();r[b+28>>2]=(c%4!==0||c%100===0&&c%400!==0?mc:lc)[a.getMonth()]+a.getDate()-1|0;r[b+36>>2]=-(a.getTimezoneOffset()*60);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();r[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Eb:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,
0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();t[a>>2]=Math.max(f,e)*60;r[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(A(a,p,c,17),A(b,p,d,17)):(A(a,p,d,17),A(b,p,c,17))},Tb:function(a,b,c){if(!(a>=0&&a<=3))return 28;w[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},q:(a,b,c)=>{b=oc(b,c);return me[a](...b)},b:(a,b,c)=>{b=oc(b,c);
return me[a](...b)},wa:(a,b,c)=>{b=oc(b,c);return me[a](...b)},Yb:()=>{Mc();rc=null},Sb:()=>Date.now(),ca:()=>{if(!N.fullscreenEnabled())return-1;Rc();var a=Vc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Vb:function(a){if(R.has(a)){var b=R.get(a),c=R;c.Uc[a]=void 0;c.Xc.push(a);b.readyState>0&&b.readyState<4&&b.abort()}},cc:()=>globalThis.devicePixelRatio??1,fc:(a,b,c)=>{a=
O(a);if(!a)return-4;a=jd(a);u[b>>3]=a.width;u[c>>3]=a.height;return 0},c:()=>performance.now(),dc:(a,b)=>{r[a>>2]=screen.width;r[b>>2]=screen.height},Xb:()=>!ba,da:(a,b,c)=>kd(a,{Ed:r[c>>2],vd:r[c+4>>2],me:r[c+8>>2],he:b,kd:r[c+12>>2],Od:r[c+16>>2]}),wb:a=>{var b=p.length;a>>>=0;if(a>1073741824)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(1073741824,Math.ceil(Math.max(a,d)/65536)*65536)-ya.buffer.byteLength+65535)/65536|0;try{ya.grow(d);xa();var e=1;break a}catch(f){}e=
void 0}if(e)return!0}return!1},ia:(a,b,c,d)=>ld(a,b,c,d,12,"blur"),ba:ad,gc:(a,b,c)=>{a=O(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},ja:(a,b,c,d)=>ld(a,b,c,d,13,"focus"),ga:(a,b,c,d)=>{if(!N.fullscreenEnabled())return-1;a=O(a);if(!a)return-4;md(a,b,c,d,"webkitfullscreenchange");return md(a,b,c,d,"fullscreenchange")},ta:(a,b,c,d)=>nd(a,b,c,d,2,"keydown"),sa:(a,b,c,d)=>nd(a,b,c,d,3,"keyup"),ec:(a,b,c,d)=>{Lc(()=>P(a)(b),c,d,b)},qa:(a,b,c,d)=>pd(a,b,c,d,5,"mousedown"),ra:(a,
b,c,d)=>pd(a,b,c,d,8,"mousemove"),pa:(a,b,c,d)=>pd(a,b,c,d,6,"mouseup"),fa:(a,b,c,d)=>document.body?.requestPointerLock?(a=O(a))?qd(a,b,c,d):-4:-1,ha:(a,b,c,d)=>rd(a,b,c,d),ka:(a,b,c,d)=>sd(a,b,c,d,25,"touchcancel"),ma:(a,b,c,d)=>sd(a,b,c,d,23,"touchend"),la:(a,b,c,d)=>sd(a,b,c,d,24,"touchmove"),na:(a,b,c,d)=>sd(a,b,c,d,22,"touchstart"),ea:(a,b,c)=>Vc[1]?td(a,b,c):-4,oa:(a,b,c,d)=>(a=O(a))?typeof a.onwheel!="undefined"?ud(a,b,c,d):-1:-4,Wb:function(a,b,c,d,e){function f(C){F?C():Jc(C)}var g=a+108,
h=t[g+36>>2],k=t[g+40>>2],q=t[g+44>>2],y=t[g+48>>2],z=t[g+52>>2],F=!!(z&64),K=C=>{f(()=>{h?P(h)(C):b?.(C)})},da=C=>{f(()=>{q?P(q)(C):d?.(C)})},U=C=>{f(()=>{k?P(k)(C):c?.(C)})},ea=C=>{f(()=>{y?P(y)(C):e?.(C)})},Y=C=>{zd(C,K,U,da,ea)},na=(C,va)=>{Cd(C,va.response,V=>{f(()=>{h?P(h)(V):b?.(V)})},V=>{f(()=>{h?P(h)(V):b?.(V)})})},oa=C=>{zd(C,na,U,da,ea)},v=ic(g+0),qa=!!(z&16),G=!!(z&4);z=!!(z&32);if(v==="EM_IDB_STORE")Y=t[g+84>>2],Cd(a,p.slice(Y,Y+t[g+88>>2]),K,U);else if(v==="EM_IDB_DELETE")Ed(a,K,U);
else if(qa){if(z)return 0;zd(a,G?na:K,U,da,ea)}else Dd(a,K,z?U:G?oa:Y);return a},Ba:(a,b)=>{var c=b>>2;b={alpha:!!m[b+0],depth:!!m[b+1],stencil:!!m[b+2],antialias:!!m[b+3],premultipliedAlpha:!!m[b+4],preserveDrawingBuffer:!!m[b+5],powerPreference:Zd[r[c+2]],failIfMajorPerformanceCaveat:!!m[b+12],re:r[c+4],Ue:r[c+5],Ud:m[b+24],je:m[b+25],Xe:r[c+7],$e:m[b+32]};a=O(a);return!a||b.je?0:Yd(a,b)},B:a=>{Z==a&&(Z=0);Z===Pd[a]&&(Z=null);typeof N=="object"&&N.we(Pd[a].Sc.canvas);Pd[a]?.Sc.canvas&&(Pd[a].Sc.canvas.ed=
void 0);Pd[a]=null},hc:(a,b)=>{a=Pd[a];b=b?x(p,b):"";b.startsWith("GL_")&&(b=b.slice(3));b=="WEBGL_draw_instanced_base_vertex_base_instance"&&Fd(T);b=="WEBGL_multi_draw_instanced_base_vertex_base_instance"&&Gd(T);b=="WEBGL_multi_draw"&&(T.te=T.getExtension("WEBGL_multi_draw"));b=="EXT_polygon_offset_clamp"&&(T.le=T.getExtension("EXT_polygon_offset_clamp"));b=="EXT_clip_control"&&(T.ke=T.getExtension("EXT_clip_control"));b=="WEBGL_polygon_mode"&&(T.ze=T.getExtension("WEBGL_polygon_mode"));return!!a.Sc.getExtension(b)},
ic:()=>Z?Z.handle:0,E:a=>{Z=Pd[a];l.ctx=T=Z?.Sc;return!a||T?0:-5},bc:(a,b,c)=>{a=ae(a);if(!a)return-3;c&&c&&x(p,c);c?a.close(b||void 0,c?x(p,c):""):b?a.close(b):a.close();return 0},Y:a=>{var b=ae(a);if(!b)return-3;b.onopen=b.onerror=b.onclose=b.onmessage=null;$d.Uc[a]=void 0;$d.Xc.push(a);return 0},Zb:()=>typeof WebSocket!="undefined",_b:a=>{if(!globalThis.WebSocket)return-1;if(!a)return-5;var b=ic(t[a>>2]);b=(a=t[a+4>>2])?new WebSocket(b,(a?x(p,a):"").split(",")):new WebSocket(b);b.binaryType="arraybuffer";
return vd($d,b)},ac:(a,b,c)=>{a=ae(a);if(!a)return-3;a.send(p.subarray(b,b+c));return 0},Z:(a,b,c)=>{var d=ae(a);if(!d)return-3;d.onclose=e=>{var f=be(a);m[f+4]=e.wasClean;n[f+6>>1]=e.code;A(e.reason,p,f+8,512);P(c)(0,f,b)};return 0},_:(a,b,c)=>{var d=ae(a);if(!d)return-3;d.onerror=()=>{var e=be(a);P(c)(0,e,b)};return 0},$:(a,b,c)=>{var d=ae(a);if(!d)return-3;d.onmessage=e=>{var f=typeof e.data=="string";if(f)var g=Bd(e.data),h=bb(e.data)+1;else h=e.data.byteLength,g=Q(h),m.set(new Uint8Array(e.data),
g);e=be(a);t[e+4>>2]=g;r[e+8>>2]=h;m[e+12]=f;P(c)(0,e,b);oe(g)};return 0},aa:(a,b,c)=>{var d=ae(a);if(!d)return-3;d.onopen=()=>{var e=be(a);P(c)(0,e,b)};return 0},Qb:(a,b)=>{var c=0,d=0,e;for(e of ee()){var f=b+c;t[a+d>>2]=f;c+=A(e,p,f,Infinity)+1;d+=4}return 0},Rb:(a,b)=>{var c=ee();t[a>>2]=c.length;a=0;for(var d of c)a+=bb(d)+1;t[b>>2]=a;return 0},p:function(a){try{var b=I(a);if(b.fd===null)throw new B(8);b.Vc&&(b.Vc=null);try{b.wc.close&&b.wc.close(b)}catch(c){throw c;}finally{pb[b.fd]=null}b.fd=
null;return 0}catch(c){if(typeof L=="undefined"||c.name!=="ErrnoError")throw c;return c.xc}},Cb:function(a,b,c,d,e){d=d<-9007199254740992||d>9007199254740992?NaN:Number(d);try{if(isNaN(d))return 22;var f=I(a),g=fe(f,b,c,d);t[e>>2]=g;return 0}catch(h){if(typeof L=="undefined"||h.name!=="ErrnoError")throw h;return h.xc}},Ab:function(a,b,c,d,e){d=d<-9007199254740992||d>9007199254740992?NaN:Number(d);try{if(isNaN(d))return 22;var f=I(a),g=ge(f,b,c,d);t[e>>2]=g;return 0}catch(h){if(typeof L=="undefined"||
h.name!=="ErrnoError")throw h;return h.xc}},Ob:function(a,b,c,d){try{var e=I(a),f=fe(e,b,c);t[d>>2]=f;return 0}catch(g){if(typeof L=="undefined"||g.name!=="ErrnoError")throw g;return g.xc}},Gb:function(a,b,c,d){b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=I(a);Mb(e,b,c);w[d>>3]=BigInt(e.position);e.Vc&&b===0&&c===0&&(e.Vc=null);return 0}catch(f){if(typeof L=="undefined"||f.name!=="ErrnoError")throw f;return f.xc}},U:function(a,b,c,d){try{var e=I(a),f=ge(e,
b,c);t[d>>2]=f;return 0}catch(g){if(typeof L=="undefined"||g.name!=="ErrnoError")throw g;return g.xc}},X:(a,b,c,d,e,f,g)=>{b=dc(a,b);if(b.xc)return-6;a=b.port;var h=b.zc;b=!1;if(c&&d){var k;if(g&1||!(k=$b[h]?$b[h]:null)){if(g&8)return-2}else h=k;c=A(h,p,c,d);c+1>=d&&(b=!0)}e&&f&&(c=A(""+a,p,e,f),c+1>=f&&(b=!0));return b?-12:0},Aa:a=>T.activeTexture(a),W:(a,b)=>{T.attachShader(W[a],Nd[b])},k:(a,b)=>{a==35051?T.Sd=b:a==35052&&(T.Yc=b);T.bindBuffer(a,Jd[b])},r:(a,b,c)=>{T.bindBufferBase(a,b,Jd[c])},
s:(a,b,c,d,e)=>{T.bindBufferRange(a,b,Jd[c],d,e)},j:(a,b)=>{T.bindFramebuffer(a,Kd[b])},L:(a,b)=>{T.bindRenderbuffer(a,Ld[b])},za:(a,b)=>{T.bindSampler(a,Qd[b])},v:(a,b)=>{T.bindTexture(a,Md[b])},gb:a=>{T.bindVertexArray(Od[a])},Ia:(a,b)=>T.blendEquationSeparate(a,b),Ja:(a,b,c,d)=>T.blendFuncSeparate(a,b,c,d),G:(a,b,c,d,e,f,g,h,k,q)=>T.blitFramebuffer(a,b,c,d,e,f,g,h,k,q),bb:(a,b,c,d)=>{c&&b?T.bufferData(a,p,d,c,b):T.bufferData(a,b,d)},ab:(a,b,c,d)=>{var e=p;c&&T.bufferSubData(a,b,e,d,c)},Qa:(a,b,
c,d)=>T.clearBufferfi(a,b,c,d),C:(a,b,c)=>{T.clearBufferfv(a,b,Ba,c>>2)},Pa:(a,b,c)=>{T.clearBufferiv(a,b,r,c>>2)},F:(a,b,c,d)=>{T.colorMask(!!a,!!b,!!c,!!d)},ob:a=>{T.compileShader(Nd[a])},K:(a,b,c,d,e,f,g,h,k)=>{T.Yc||!h?T.compressedTexSubImage2D(a,b,c,d,e,f,g,h,k):T.compressedTexSubImage2D(a,b,c,d,e,f,g,p,k,h)},H:(a,b,c,d,e,f,g,h,k,q,y)=>{T.Yc?T.compressedTexSubImage3D(a,b,c,d,e,f,g,h,k,q,y):T.compressedTexSubImage3D(a,b,c,d,e,f,g,h,k,p,y,q)},$a:(a,b,c,d,e)=>T.copyBufferSubData(a,b,c,d,e),$b:()=>
{var a=Vd(W),b=T.createProgram();b.name=a;b.pd=b.nd=b.od=0;b.Jd=1;W[a]=b;return a},Bb:a=>{var b=Vd(Nd);Nd[b]=T.createShader(a);return b},P:a=>T.cullFace(a),va:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=Jd[d];e&&(T.deleteBuffer(e),e.name=0,Jd[d]=null,d==T.Sd&&(T.Sd=0),d==T.Yc&&(T.Yc=0))}},l:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+c*4>>2],e=Kd[d];e&&(T.deleteFramebuffer(e),e.name=0,Kd[d]=null)}},x:a=>{if(a){var b=W[a];b?(T.deleteProgram(b),b.name=0,W[a]=null):X||=1281}},ua:(a,b)=>{for(var c=0;c<
a;c++){var d=r[b+c*4>>2],e=Ld[d];e&&(T.deleteRenderbuffer(e),e.name=0,Ld[d]=null)}},N:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=Qd[d];e&&(T.deleteSampler(e),e.name=0,Qd[d]=null)}},m:a=>{if(a){var b=Nd[a];b?(T.deleteShader(b),Nd[a]=null):X||=1281}},S:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=Md[d];e&&(T.deleteTexture(e),e.name=0,Md[d]=null)}},Ua:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2];T.deleteVertexArray(Od[d]);Od[d]=null}},O:a=>T.depthFunc(a),w:a=>{T.depthMask(!!a)},Ra:(a,b)=>
T.depthRange(a,b),R:(a,b)=>{T.detachShader(W[a],Nd[b])},h:a=>T.disable(a),Ca:a=>{T.disableVertexAttribArray(a)},Ka:(a,b,c)=>{T.drawArrays(a,b,c)},La:(a,b,c,d)=>{T.drawArraysInstanced(a,b,c,d)},M:(a,b)=>{for(var c=he[a],d=0;d<a;d++)c[d]=r[b+d*4>>2];T.drawBuffers(c)},Ma:(a,b,c,d)=>{T.drawElements(a,b,c,d)},Na:(a,b,c,d,e)=>{T.drawElementsInstanced(a,b,c,d,e)},g:a=>T.enable(a),Ga:a=>{T.enableVertexAttribArray(a)},o:(a,b,c,d)=>{T.framebufferRenderbuffer(a,b,c,Ld[d])},d:(a,b,c,d,e)=>{T.framebufferTexture2D(a,
b,c,Md[d],e)},n:(a,b,c,d,e)=>{T.framebufferTextureLayer(a,b,Md[c],d,e)},fb:a=>T.frontFace(a),cb:(a,b)=>{Wd(a,b,"createBuffer",Jd)},t:(a,b)=>{Wd(a,b,"createFramebuffer",Kd)},Ya:(a,b)=>{Wd(a,b,"createRenderbuffer",Ld)},_a:(a,b)=>{Wd(a,b,"createSampler",Qd)},Wa:(a,b)=>{Wd(a,b,"createTexture",Md)},hb:(a,b)=>{Wd(a,b,"createVertexArray",Od)},eb:(a,b)=>je(a,b,2),a:(a,b)=>je(a,b,0),nb:(a,b,c,d)=>{a=T.getProgramInfoLog(W[a]);a===null&&(a="(unknown error)");b=b>0&&d?A(a,p,d,b):0;c&&(r[c>>2]=b)},T:(a,b,c)=>
{if(c)if(a>=Id)X||=1281;else if(a=W[a],b==35716)a=T.getProgramInfoLog(a),a===null&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(b==35719){if(!a.pd){var d=T.getProgramParameter(a,35718);for(b=0;b<d;++b)a.pd=Math.max(a.pd,T.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.pd}else if(b==35722){if(!a.nd)for(d=T.getProgramParameter(a,35721),b=0;b<d;++b)a.nd=Math.max(a.nd,T.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.nd}else if(b==35381){if(!a.od)for(d=T.getProgramParameter(a,35382),b=0;b<d;++b)a.od=
Math.max(a.od,T.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.od}else r[c>>2]=T.getProgramParameter(a,b);else X||=1281},mb:(a,b,c,d)=>{a=T.getShaderInfoLog(Nd[a]);a===null&&(a="(unknown error)");b=b>0&&d?A(a,p,d,b):0;c&&(r[c>>2]=b)},db:a=>{var b=Rd[a];if(!b){switch(a){case 7939:b=Bd(ie().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=T.getParameter(a))||(X||=1280);b=b?Bd(b):0;break;case 7938:b=Bd(`OpenGL ES 3.0 (${T.getParameter(7938)})`);break;case 35724:b=T.getParameter(35724);
var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Bd(b);break;default:X||=1280}Rd[a]=b}return b},e:(a,b)=>{if(Z.version<2)return X||=1282,0;var c=Sd[a];if(c)return b<0||b>=c.length?(X||=1281,0):c[b];switch(a){case 7939:return c=ie().map(Bd),c=Sd[a]=c,b<0||b>=c.length?(X||=1281,0):c[b];default:return X||=1280,0}},lb:(a,b)=>T.getUniformBlockIndex(W[a],b?x(p,b):""),jb:(a,b)=>{b=b?x(p,b):"";if(a=W[a]){var c=a,d=
c.hd,e=c.fe,f;if(!d){c.hd=d={};c.ee={};var g=T.getProgramParameter(c,35718);for(f=0;f<g;++f){var h=T.getActiveUniform(c,f);var k=h.name;h=h.size;var q=ke(k);q=q>0?k.slice(0,q):k;var y=c.Jd;c.Jd+=h;e[q]=[h,y];for(k=0;k<h;++k)d[y]=k,c.ee[y++]=q}}c=a.hd;d=0;f=b;e=ke(b);e>0&&(d=b.slice(e+1),d=parseInt(d)>>>0,f=b.slice(0,e));if((e=a.fe[f])&&d<e[0]&&(d+=e[1],c[d]=c[d]||T.getUniformLocation(a,b)))return d}else X||=1281;return-1},xa:(a,b,c)=>{for(var d=he[b],e=0;e<b;e++)d[e]=r[c+e*4>>2];T.invalidateFramebuffer(a,
d)},Mb:a=>{a=W[a];T.linkProgram(a);a.hd=0;a.fe={}},u:(a,b)=>{a==3317?Td=b:a==3314&&(Ud=b);T.pixelStorei(a,b)},Ha:(a,b)=>T.polygonOffset(a,b),ya:a=>T.readBuffer(a),Xa:(a,b,c,d,e)=>T.renderbufferStorageMultisample(a,b,c,d,e),Za:(a,b,c)=>{T.samplerParameterf(Qd[a],b,c)},i:(a,b,c)=>{T.samplerParameteri(Qd[a],b,c)},Oa:(a,b,c,d)=>T.scissor(a,b,c,d),qb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=ic(t[c+f*4>>2],d?t[d+f*4>>2]:void 0);T.shaderSource(Nd[a],e)},A:(a,b,c,d)=>T.stencilFuncSeparate(a,b,c,d),D:a=>T.stencilMask(a),
z:(a,b,c,d)=>T.stencilOpSeparate(a,b,c,d),Ta:(a,b,c,d,e)=>T.texStorage2D(a,b,c,d,e),Va:(a,b,c,d,e,f)=>T.texStorage3D(a,b,c,d,e,f),J:(a,b,c,d,e,f,g,h,k)=>{if(T.Yc)T.texSubImage2D(a,b,c,d,e,f,g,h,k);else if(k){var q=le(h);T.texSubImage2D(a,b,c,d,e,f,g,h,q,k>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else{if(k){q=le(h);var y=f*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT*(Ud||e)+Td-1&-Td);k=q.subarray(k>>>31-Math.clz32(q.BYTES_PER_ELEMENT),k+y>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else k=
null;T.texSubImage2D(a,b,c,d,e,f,g,h,k)}},I:(a,b,c,d,e,f,g,h,k,q,y)=>{if(T.Yc)T.texSubImage3D(a,b,c,d,e,f,g,h,k,q,y);else if(y){var z=le(q);T.texSubImage3D(a,b,c,d,e,f,g,h,k,q,z,y>>>31-Math.clz32(z.BYTES_PER_ELEMENT))}else T.texSubImage3D(a,b,c,d,e,f,g,h,k,q,null)},ib:(a,b)=>{var c=T,d=c.uniform1i;var e=T.ge;if(e){var f=e.hd[a];typeof f=="number"&&(e.hd[a]=f=T.getUniformLocation(e,e.ee[a]+(f>0?`[${f}]`:"")));a=f}else X||=1282,a=void 0;d.call(c,a,b)},kb:(a,b,c)=>{a=W[a];T.uniformBlockBinding(a,b,c)},
Q:a=>{a=W[a];T.useProgram(a);T.ge=a},Fa:(a,b)=>{T.vertexAttribDivisor(a,b)},Ea:(a,b,c,d,e)=>{T.vertexAttribIPointer(a,b,c,d,e)},Da:(a,b,c,d,e,f)=>{T.vertexAttribPointer(a,b,c,!!d,e,f)},Sa:(a,b,c,d)=>T.viewport(a,b,c,d),Hb:(a,b)=>Ua(p.subarray(a,a+b))};function qe(a=[]){var b=ne;a.unshift(ha);var c=a.length,d=Wc((c+1)*4),e=d,f;for(f of a)t[e>>2]=Xc(f),e+=4;t[e>>2]=0;try{var g=b(c,d);wa=g;zc(g)}catch(h){Ac(h)}}
function re(a=fa){function b(){l.calledRun=!0;if(!ua){M.root=Fb(M,null);if(!l.noFSInit&&!sb){var c,d;sb=!0;c??=l.stdin;d??=l.stdout;e??=l.stderr;c?Ob("stdin",c):Ib("/dev/tty","/dev/stdin");d?Ob("stdout",null,d):Ib("/dev/tty","/dev/stdout");e?Ob("stderr",null,e):Ib("/dev/tty1","/dev/stderr");Lb("/dev/stdin",0);Lb("/dev/stdout",1);Lb("/dev/stderr",1)}se.kc();tb=!1;l.onRuntimeInitialized?.();l.noInitialRun||qe(a);if(l.postRun)for(typeof l.postRun=="function"&&(l.postRun=[l.postRun]);l.postRun.length;){var e=
l.postRun.shift();Ja.push(e)}Ia(Ja)}}if(Ma>0)Na=re;else{if(l.preRun)for(typeof l.preRun=="function"&&(l.preRun=[l.preRun]);l.preRun.length;)La();Ia(Ka);Ma>0?Na=re:l.setStatus?(l.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>l.setStatus(""),1);b()},1)):b()}}var se;
(async function(){function a(c){c=se=c.exports;ne=l._main=c.mc;oe=c.nc;Q=c.oc;Ad=c.pc;Vb=c.qc;cc=c.rc;Zc=c.sc;Wc=c.tc;Yc=c.uc;ya=c.jc;ed=c.lc;xa();Oa();return se}Pa();var b={a:pe};if(l.instantiateWasm)return new Promise(c=>{l.instantiateWasm(b,(d,e)=>{c(a(d,e))})});Da??=l.locateFile?l.locateFile("Tileon_Editor.wasm",ka):ka+"Tileon_Editor.wasm";return function(c){return a(c.instance)}(await Ga(b))})();re();
